### ISSUE TITLE
Function re.search not finding the given regex

### ISSUE THREAD

**Issue by CarlosVergaraCh** [googleads/google-ads-python#745] opened 2023-02-15 11:02 UTC
Describe the bug:
When recieving the accepted permissions the re.search (line 164) does not find the regex given. This provoques a NoneType Error in the next line.
Steps to Reproduce:
Just execute the code (.py) given in this repository (https://github.com/googleads/google-ads-python/blob/9f52ec2b558499ada7b3688e8948844b61d3ddc1/examples/authentication/generate_user_credentials.py#L164)
Expected behaviour:
The re.search finds de given regex.
Solution: 
Changing re.search to re.match

Client library version: Python 3.10.6
Google Ads API version: 19.0.0

**Comment by BenRKarl** [comment] 2023-02-23 18:40
@CarlosVergaraCh I'm unable to reproduce this. When I paste the URL that's printed to console in my browser and follow the Auth steps, the refresh token is parsed and printed as expected.

However if I _don't_ paste the URL into my browser and let the script time out, I get this error:

`AttributeError: 'NoneType' object has no attribute 'group'`

Is it possible you're not completing the steps to Authenticate before the script times out?

**Comment by BenRKarl** [comment] 2023-03-14 18:21
@CarlosVergaraCh closing this out for now, if you continue seeing this problem please comment here with more details.

**Closed by BenRKarl** 2023-03-14 18:21 UTC
