### ISSUE TITLE
AttributeError: module 'google.ads.google_ads.v2.proto.errors' has no attribute 'errors_pb2'

### ISSUE THREAD

**Issue by rubberviscous** [googleads/google-ads-python#201] opened 2020-01-13 20:23 UTC
When running the example `create_and_attach_shared_keyword_set.py` with the latest `4.1.1` release, I'm getting the following error. 

```Created shared set "customers/{obfuscated}/sharedSets/{obfuscated}".
Created shared criterion "customers/{obfuscated}/sharedCriteria/{obfuscated}~{obfuscated}".
Created shared criterion "customers/{obfuscated}/sharedCriteria/{obfuscated}~{obfuscated}".
Request made: ClientCustomerId: {obfuscated}, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v2.services.CampaignSharedSetService/MutateCampaignSharedSets, RequestId: None, IsFault: True, FaultMessage: None
Traceback (most recent call last):
  File "/Users/{obfuscated}/Projects/google-ads-python/examples/advanced_operations/create_and_attach_shared_keyword_set.py", line 130, in <module>
    main(google_ads_client, args.customer_id, args.campaign_id)
  File "/Users/{obfuscated}/Projects/google-ads-python/examples/advanced_operations/create_and_attach_shared_keyword_set.py", line 99, in main
    customer_id, [campaign_set_operation]).results[0].resource_name)
  File "/Users/{obfuscated}/.local/share/virtualenvs/google-ads-python-ObS9Yvf7/lib/python3.7/site-packages/google/ads/google_ads/v2/services/campaign_shared_set_service_client.py", line 402, in mutate_campaign_shared_sets
    return self._inner_api_calls['mutate_campaign_shared_sets'](request, retry=retry, timeout=timeout, metadata=metadata)
  File "/Users/{obfuscated}/.local/share/virtualenvs/google-ads-python-ObS9Yvf7/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/{obfuscated}/.local/share/virtualenvs/google-ads-python-ObS9Yvf7/lib/python3.7/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/Users/{obfuscated}/.local/share/virtualenvs/google-ads-python-ObS9Yvf7/lib/python3.7/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/Users/{obfuscated}/.local/share/virtualenvs/google-ads-python-ObS9Yvf7/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/Users/{obfuscated}/.local/share/virtualenvs/google-ads-python-ObS9Yvf7/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/Users/{obfuscated}/.local/share/virtualenvs/google-ads-python-ObS9Yvf7/lib/python3.7/site-packages/grpc/_interceptor.py", line 222, in __call__
    compression=compression)
  File "/Users/{obfuscated}/.local/share/virtualenvs/google-ads-python-ObS9Yvf7/lib/python3.7/site-packages/grpc/_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "/Users/{obfuscated}/.local/share/virtualenvs/google-ads-python-ObS9Yvf7/lib/python3.7/site-packages/grpc/_interceptor.py", line 126, in result
    raise self._exception
  File "/Users/{obfuscated}/.local/share/virtualenvs/google-ads-python-ObS9Yvf7/lib/python3.7/site-packages/grpc/_interceptor.py", line 248, in continuation
    compression=new_compression)
  File "/Users/{obfuscated}/.local/share/virtualenvs/google-ads-python-ObS9Yvf7/lib/python3.7/site-packages/grpc/_interceptor.py", line 272, in with_call
    compression=compression)
  File "/Users/{obfuscated}/.local/share/virtualenvs/google-ads-python-ObS9Yvf7/lib/python3.7/site-packages/grpc/_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "/Users/{obfuscated}/.local/share/virtualenvs/google-ads-python-ObS9Yvf7/lib/python3.7/site-packages/grpc/_interceptor.py", line 126, in result
    raise self._exception
  File "/Users/{obfuscated}/.local/share/virtualenvs/google-ads-python-ObS9Yvf7/lib/python3.7/site-packages/grpc/_interceptor.py", line 248, in continuation
    compression=new_compression)
  File "/Users/{obfuscated}/.local/share/virtualenvs/google-ads-python-ObS9Yvf7/lib/python3.7/site-packages/grpc/_interceptor.py", line 272, in with_call
    compression=compression)
  File "/Users/{obfuscated}/.local/share/virtualenvs/google-ads-python-ObS9Yvf7/lib/python3.7/site-packages/grpc/_interceptor.py", line 256, in _with_call
    continuation, client_call_details, request)
  File "/Users/{obfuscated}/.local/share/virtualenvs/google-ads-python-ObS9Yvf7/lib/python3.7/site-packages/google/ads/google_ads/interceptors/exception_interceptor.py", line 139, in intercept_unary_unary
    self._handle_grpc_failure(response)
  File "/Users/{obfuscated}/.local/share/virtualenvs/google-ads-python-ObS9Yvf7/lib/python3.7/site-packages/google/ads/google_ads/interceptors/exception_interceptor.py", line 105, in _handle_grpc_failure
    google_ads_failure = self._get_google_ads_failure(trailing_metadata)
  File "/Users/{obfuscated}/.local/share/virtualenvs/google-ads-python-ObS9Yvf7/lib/python3.7/site-packages/google/ads/google_ads/interceptors/exception_interceptor.py", line 68, in _get_google_ads_failure
    ga_failure = error_protos.errors_pb2.GoogleAdsFailure()
AttributeError: module 'google.ads.google_ads.v2.proto.errors' has no attribute 'errors_pb2
```

**Comment by wihl** [comment] 2020-01-13 20:49
Duplicate of #200

**Closed by wihl** 2020-01-13 20:49 UTC
