### ISSUE TITLE
Linking 2 manager accounts returns 500 error from google

### ISSUE THREAD

**Issue by asafzinger** [googleads/google-ads-python#159] opened 2019-07-18 09:01 UTC
I'm trying to create a link between 2 manager customers using this code:

```
client_link_operation = client.get_type('CustomerClientLinkOperation')
client_link = client_link_operation.create
client_link.client_customer.value = f'customers/{mgr_d}'
client_link.status = new_mgr_client.get_type('ManagerLinkStatusEnum').PENDING
       
response = client.mutate_customer_client_link(new_mgr_id, client_link_operation)
```
I get "google.api_core.exceptions.InternalServerError: 500 Internal error encountered." 
To my understanding, this operation should be supported

**Comment by BenRKarl** [comment] 2019-07-19 15:29
Hi @asafzinger thank you for reporting this. This may be an API issue that's better reported in the [support forum](https://groups.google.com/forum/#!forum/adwords-api), but before I point you there I'd like to double-check that it isn't an issue with this library. Do you have a `request-id` from a recent failed request that I could use to investigate further? If it's easier you can just paste an entire response payload here. Thanks!

**Comment by asafzinger** [comment] 2019-07-21 07:33
Thanks @BenRKarl ,
Here is the full exception message:
```
Request made: ClientCustomerId: 6504598609 , Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v2.services.CustomerClientLinkService/MutateCustomerClientLink, RequestId: None, IsFault: True, FaultMessage: Internal error encountered.
Traceback (most recent call last):
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/grpc/_interceptor.py", line 222, in __call__
    compression=compression)
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/grpc/_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/grpc/_channel.py", line 295, in result
    raise self
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/grpc/_interceptor.py", line 248, in continuation
    compression=new_compression)
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/grpc/_interceptor.py", line 272, in with_call
    compression=compression)
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/grpc/_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/grpc/_channel.py", line 295, in result
    raise self
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/grpc/_interceptor.py", line 248, in continuation
    compression=new_compression)
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/grpc/_interceptor.py", line 272, in with_call
    compression=compression)
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/grpc/_interceptor.py", line 256, in _with_call
    continuation, client_call_details, request)
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/google/ads/google_ads/client.py", line 339, in intercept_unary_unary
    self._handle_grpc_failure(response)
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/google/ads/google_ads/client.py", line 318, in _handle_grpc_failure
    raise exception
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/grpc/_interceptor.py", line 248, in continuation
    compression=new_compression)
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/grpc/_channel.py", line 576, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Internal error encountered."
	debug_error_string = "{"created":"@1563694278.435668363","description":"Error received from peer ipv4:172.217.169.10:443","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"Internal error encountered.","grpc_status":13}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/asaf/git/ml-googleapi/app/main/service/google_service.py", line 384, in <module>
    link_customer_to_mgr(ml_asaf60, ml_asaf50, ml_asaf_50_manager_id, ml_asaf_50_manager_id, ml_asaf_60_manager_id)
  File "/home/asaf/git/ml-googleapi/app/main/service/google_service.py", line 203, in link_customer_to_mgr
    response = customer_client_link_service.mutate_customer_client_link(new_mgr_id, client_link_operation)
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/google/ads/google_ads/v2/services/customer_client_link_service_client.py", line 287, in mutate_customer_client_link
    return self._inner_api_calls['mutate_customer_client_link'](request, retry=retry, timeout=timeout, metadata=metadata)
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/google/api_core/retry.py", line 273, in retry_wrapped_func
    on_error=on_error,
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/google/api_core/retry.py", line 182, in retry_target
    return target()
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/asaf/.local/share/virtualenvs/ml-googleapi-n6J6a0FH/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InternalServerError: 500 Internal error encountered.
```

**Comment by BenRKarl** [comment] 2020-04-15 20:01
@asafzinger are you still having this issue? From what I can tell it might have been caused by a temporary server issue that's since been resolved.

**Comment by BenRKarl** [comment] 2020-04-20 13:04
Closing this at it's outdated and likely fixed, but please reopen if it continues to be a problem.

**Closed by BenRKarl** 2020-04-20 13:04 UTC
