### ISSUE TITLE
Problem trying to access Google Ads Api v6 from google-ads python library version 4.0.0

### ISSUE THREAD

**Issue by Joao-Lamesa** [googleads/google-ads-python#445] opened 2021-06-10 16:20 UTC
We have a dag on Cloud Composer+Airflow (composer version 1.10.15, airflow 1.10.6).

When trying to upload data files to google ads api via implementation of a BaseHook. Summarizing, we implement the hook as follows:

```
from airflow.hooks.base_hook import BaseHook
...

class BaseGoogleAdsHook(BaseHook):
    def __init__(self, conn_id="google_ads_connection", customer_id=None, version="v6", page_size=100):
        super().__init__(None)
        self.conn_id = conn_id
        self.extras = self.get_connection(self.conn_id).extra_dejson
        self.credential_dict = json.loads(self.extras.get("extra__google_cloud_platform__keyfile_dict", None))
        self._conn = None
        self.api_version = version
        self.customer_id = customer_id
        self.page_size = page_size

```
However, using google-ads library 4.0.0, we get the error:

`ValueError: Specified Google Ads API version "v6" does not exist. Valid API versions are: "v2", "v1`

We have to use google-ads 4.0.0 because of compatibility with composer+airflow image version. If I try to call v2 or v1 as required in error message, I get an error related to assigning gclid field.

We have another composer instance with a near out-of-support composer+airflow version (1.10.5+1.10.6, respectively). **This accepts google-ads version 9.0.0 and the same dag runs fine**.

What may be happening? since v6 ads api does exist?

**Comment by davedavis** [comment] 2021-06-10 16:37
Version 4 is now deprecated (I think!) but there was a contribution merged into V6 that added compatibility with the composer version of Airflow (Python 3.7 was the limiting factor I believe)

The issue is here: https://github.com/googleads/google-ads-python/issues/331

I've been using it with composer since then. Have you tried upgrading to V6 or 7 (or the release that adds support for these versions)?

**Comment by Joao-Lamesa** [comment] 2021-06-10 16:48
How did you install version 7.0.0 on Cloud Composer?

When I tried it with the Composer UI, I got:

```
ERROR: Could not find a version that satisfies the requirement google-ads==7.0.0 (from -r requirements.txt (line 1)) (from versions: 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.5.2, 0.6.0, 0.7.0, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.4.0, 2.4.1, 3.0.0, 3.1.0, 3.1.1, 3.1.2, 3.2.0, 3.3.0, 4.0.0, 8.1.0, 8.2.0, 9.0.0, 10.0.0, 11.0.0, 11.0.1, 11.0.2)
ERROR: No matching distribution found for google-ads==7.0.0 (from -r requirements.txt (line 1))
```

**Comment by davedavis** [comment] 2021-06-10 18:28
https://github.com/googleads/google-ads-python/releases/tag/8.1.0

That's the first release that supports 3.7, the version composer is running on.

**Comment by davedavis** [comment] 2021-06-10 21:27
Yea, the first preview (whoops) actually now, but I was using an earlier one prior.

Is upgrading not a possibility? Even to a slightly more recent version? If so, how new can you go?

**Comment by Joao-Lamesa** [comment] 2021-06-10 23:11
We have just upgraded to the version right before the preview ones (composer-1.16.6-airflow-1.10.15). Now, upgrading is not possible because Composer does not allow upgrading from Airflow 1.x to 2.x. We will have to create yet another instance, and then move all the dags, vars and conns.

**Comment by Joao-Lamesa** [comment] 2021-06-15 09:47
@davedavis **We have not been able to run google-ads==8.1.0 on airflow2.0.1+composer** version because of incompatibilities. **But we have been able to use google-ads==7.0.0 which is installed in the environment by default. With that version, we could access google ads API v5 instead of v6 for us**.

Thannk you.

**Comment by davedavis** [comment] 2021-06-15 10:30
Ahh brilliant. Delighted you got it sorted.

**Comment by BenRKarl** [comment] 2021-06-15 17:51
Hey All - we released version `12.0.0` of the library today, which is compatible with Python 3.6 and thus should be usable in Composer. It is only compatible with API versions v6, v7 and v8, however. It's also the last release that will be compatible with Python 3.6, as we prepare for its EOL at the end of this year. When using Composer, I recommend upgrading to version `12.0.0` and using `v8` as that should be a stable environment well into 2022. My hope is that Composer enables Python versions greater than 3.6 well before then.

**Comment by Joao-Lamesa** [comment] 2021-07-20 14:46
Hi, now v5 got deprecated on google ads API. ANd cloud Composer won´t let me upgrade google-ads==7.0.0 pypi package, which is pre-installed, to version 12.0.0.

Have you got a similiar issue?

error msg:

apache-airflow-providers-google 3.0.0 requires google-ads<8.0.0,>=4.0.0, but you'll have google-ads 12.0.0 which is incompatible.

**Comment by BenRKarl** [comment] 2021-08-09 17:36
@Joao-Lamesa this is an issue that Composer needs to resolve on their end to allow the appropriate versions of this library, would you please file an issue with them?

**Closed by BenRKarl** 2021-08-09 17:36 UTC
Labels: bug, triage
