### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by skiwan** [googleads/google-ads-python#316] opened 2020-09-24 16:09 UTC
Hello again :)

We are currently running into internal server errors while using the current version of the api
(upgraded python package yesterday, using "v5" for all services and enums)

The Internal Server Error 500 occurs during different request. Following log is from a ad group creation request

(further down is the normal error [not log] from another request that created the error)

[2020-09-24 17:06:03,141 - INFO] Request made: ClientCustomerId: 9465697505, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v5.services.AdGroupAdService/MutateAdGroupAds, RequestId: 4bG9J784iF2w2KPjTSrHfg, IsFault: False, FaultMessage: None
[2020-09-24 17:07:03,458 - INFO] Request
-------
Method: /google.ads.googleads.v5.services.AdGroupAdService/MutateAdGroupAds
Host: googleads.googleapis.com:443
Headers: {
  "developer-token": "REDACTED",
  "login-customer-id": "4156396339",
  "x-goog-api-client": "gl-python/3.8.0 grpc/1.32.0 gax/1.22.2 gapic/7.0.0",
  "x-goog-request-params": "customer_id=9465697505"
}
Request: customer_id: "9465697505"
operations {
  create {
    status: PAUSED
    ad {
      expanded_dynamic_search_ad {
        description: "Wide range of high-performance motorcycle gear. Everything for you and your bike."
        description2: "Falling down is allowed. Getting back up is mandatory. Get up and ride with www.24mx.ie"
      }
    }
    ad_group: "customers/9465697505/adGroups/109837526837"
  }
}

Response
-------
Headers: {
  "google.ads.googleads.v5.errors.googleadsfailure-bin": "\n%\n\u0002P\u0002\u0012\u001fAn internal error has occurred.",
  "grpc-status-details-bin": "\b\r\u0012\u001bInternal error encountered.\u001an\nCtype.googleapis.com/google.ads.googleads.v5.errors.GoogleAdsFailure\u0012'\n%\n\u0002P\u0002\u0012\u001fAn internal error has occurred.",
  "request-id": "fJwJJxoKVn0SCTSMhYEy9g"
}
Fault: {
  "created": "@1600960023.458000000",
  "description": "Error received from peer ipv4:172.217.22.170:443",
  "file": "src/core/lib/surface/call.cc",
  "file_line": 1062,
  "grpc_message": "Internal error encountered.",
  "grpc_status": 13
}

[2020-09-24 17:07:03,458 - WARNING] Request made: ClientCustomerId: 9465697505, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v5.services.AdGroupAdService/MutateAdGroupAds, RequestId: fJwJJxoKVn0SCTSMhYEy9g, IsFault: True, FaultMessage: Internal error encountered.
Traceback (most recent call last):
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 216, in __call__
    response, ignored_call = self._with_call(request,
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_channel.py", line 333, in result
    raise self
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 241, in continuation
    response, call = self._thunk(new_method).with_call(
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 266, in with_call
    return self._with_call(request,
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_channel.py", line 333, in result
    raise self
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 241, in continuation
    response, call = self._thunk(new_method).with_call(
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 266, in with_call
    return self._with_call(request,
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 254, in _with_call
    call = self._interceptor.intercept_unary_unary(continuation,
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\ads\google_ads\interceptors\exception_interceptor.py", line 169, in intercept_unary_unary
    self._handle_grpc_failure(response)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\ads\google_ads\interceptors\exception_interceptor.py", line 141, in _handle_grpc_failure
    raise self._get_error_from_response(response)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 241, in continuation
    response, call = self._thunk(new_method).with_call(
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_channel.py", line 837, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Internal error encountered."
        debug_error_string = "{"created":"@1600960023.458000000","description":"Error received from peer ipv4:172.217.22.170:443","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Internal error encountered.","grpc_status":13}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dsa_campaign_script.py", line 848, in <module>
    create_expanded_dsa(client, google_ads_id, ad_group_res_name, ad_group_ad_service, descr)
  File "dsa_campaign_script.py", line 376, in create_expanded_dsa
    ad_group_ad_response = ad_group_ad_service.mutate_ad_group_ads(
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\ads\google_ads\v5\services\ad_group_ad_service_client.py", line 313, in mutate_ad_group_ads
    return self._inner_api_calls['mutate_ad_group_ads'](request, retry=retry, timeout=timeout, metadata=metadata)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\gapic_v1\method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\retry.py", line 184, in retry_target
    return target()
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InternalServerError: 500 Internal error encountered.

___________________________________________________________

We also received the error from a search stream request , here the normal python error raised 

Request made: ClientCustomerId: 9465697505, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v5.services.GoogleAdsService/SearchStream, RequestId: iHEC1DYKDx_DKsKEciJxrQ, IsFault: True, FaultMessage: Internal error encountered.
Traceback (most recent call last):
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\grpc_helpers.py", line 150, in error_remapped_callable
    return _StreamingResponseIterator(result, prefetch_first_result=prefetch_first)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\grpc_helpers.py", line 73, in __init__
    self._stored_first_result = six.next(self._wrapped)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\ads\google_ads\interceptors\exception_interceptor.py", line 100, in __next__
    raise e
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\ads\google_ads\interceptors\exception_interceptor.py", line 97, in __next__
    self._failure_handler(self._underlay_call)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\ads\google_ads\interceptors\exception_interceptor.py", line 141, in _handle_grpc_failure
    raise self._get_error_from_response(response)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\ads\google_ads\interceptors\exception_interceptor.py", line 92, in __next__
    return next(self._underlay_call)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_channel.py", line 416, in __next__
    return self._next()
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_channel.py", line 706, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Internal error encountered."
        debug_error_string = "{"created":"@1600961955.671000000","description":"Error received from peer ipv4:216.58.211.10:443","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Internal error encountered.","grpc_status":13}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dsa_campaign_script.py", line 790, in <module>
    ad_groups = get_all_adgroups_for_campaign_id(client, google_ads_id, ga_service=ga_service, campaign_id=campaign_id)
  File "dsa_campaign_script.py", line 107, in get_all_adgroups_for_campaign_id
    response = ga_service.search_stream(customer_id, query=query)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\ads\google_ads\v5\services\google_ads_service_client.py", line 326, in search_stream
    return self._inner_api_calls['search_stream'](request, retry=retry, timeout=timeout, metadata=metadata)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\gapic_v1\method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\retry.py", line 184, in retry_target
    return target()
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\grpc_helpers.py", line 152, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InternalServerError: 500 Internal error encountered.

The error seems not to be tied to any specific request type or timing.
The Script itself creates campaigns, add custom feed and location targetting to the campaign, ads agroups, ads and custom labels for the feed. Overall the Error seems to occur after about 20-30 created campaigns.

If any more information is needed please let me know

BR

**Comment by skiwan** [comment] 2020-09-29 07:38
This problem seems to originate from asynchronicity within the API

I addition to the 500 we are receiving a lot of "Multiple requests were attempting to modify the same resource at once. Please retry the request" which at least in theory doesn't make sense to me having a non parallel program. 

With those problems occurring I think the problem might come from the fact that the API sends an answer back from a API request before it actually finished the api call completely, which in return lets our script send another api call leading to asynchronous behavior which causes error in the API

Im unsure if this problem originates from using v5 of from creating DSA's

**Comment by theo-funnel** [comment] 2020-10-19 12:17
We've encountered the same error when trying to stream data from one specific account. Modifying the query does not change the outcome, and the same query works for all other accounts we've tried, so it seems to be bound to that specific account. As far as I can tell there's nothing special about it though.

`grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Internal error encountered."
        debug_error_string = "{"created":"@1603108651.038928000","description":"Error received from peer ipv4:172.217.21.170:443","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Internal error encountered.","grpc_status":13}"
`

**Comment by BenRKarl** [comment] 2021-04-13 18:46
@skiwan and @theo-funnel sorry for the delayed response. Are you two still having these issues? The 500 errors could be a separate issue in the API that aren't being handled by the client library properly. If you're still able to reproduce them then I can try to pinpoint the underlying issue.

**Comment by theo-funnel** [comment] 2021-04-14 11:24
@BenRKarl I dug out the old credential/account combination we had this problem with and when attempting a download now we get a proper error:

`{'errors': [{'errorCode': {'authorizationError': 'ACCESS_DENIED_FOR_ACCOUNT_TYPE'}, 'message': "The customer (or login customer) isn't in Google Ads. It belongs to another ads system."}]}`

I don't know if we were supposed to be getting this error all along, or if something has changed with the customer since we encountered this issue.

**Comment by skiwan** [comment] 2021-04-14 12:15
Ill investigate an come back to you as soon as I have more info

**Comment by BenRKarl** [comment] 2021-04-14 14:32
@theo-funnel my suspicion is that's the error you should have been receiving all along. I think the underlying error here was probably fixed before I could identify it. 

I'm going to close this one out, but @skiwan if you are able to reproduce the internal error please reopen!

**Closed by BenRKarl** 2021-04-14 14:32 UTC
Labels: bug

**Comment by skiwan** [comment] 2021-04-19 05:29
Hey @BenRKarl 

Did some investigating again.
As we are still using v5 of the library the errors are still occuring.

Infrequent and hard to replicate. Following is the log of the most recent request that threw a 500 at us. Just as a note, I executed the exact same request again and did not run into the same error. I have a hunch that the problem might occure when a service has been initiallized and used for quite a while in a row (the script that currently produces this error runs for quite a while (up to 1h)

_________________________---


[2021-04-16 17:19:03,380 - INFO] Request made: ClientCustomerId: 9053560327, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v5.services.GoogleAdsService/Search, RequestId: fJKUXUPA_QpJ5VGdjJm6Kg, IsFault: False, FaultMessage: None
[2021-04-16 17:19:13,715 - INFO] Request
-------
Method: /google.ads.googleads.v5.services.GoogleAdsService/Search
Host: googleads.googleapis.com:443
Headers: {
  "developer-token": "REDACTED",
  "login-customer-id": "4156396339",
  "x-goog-api-client": "gl-python/3.8.0 grpc/1.36.1 gax/1.26.1 gapic/9.0.0",
  "x-goog-request-params": "customer_id=9053560327"
}
Request: customer_id: "9053560327"
query: "\n\tSELECT ad_group_criterion.resource_name\n\t, ad_group_criterion.listing_group.type \n\t, ad_group_criterion.listing_group.case_value.product_custom_attribute.value\n\t, ad_group_criterion.listing_group.case_value.product_custom_attribute.index\n\t, ad_group_criterion.listing_group.parent_ad_group_criterion\n\tFROM ad_group_criterion  WHERE ad_group_criterion.type = LISTING_GROUP AND ad_group_criterion.listing_group.type = \"UNIT\" AND ad_group_criterion.listing_group.case_value.product_custom_attribute.value Is not NULL AND ad_group.id = 118150352364"


Response
-------
Headers: {
  "google.ads.googleads.v5.errors.googleadsfailure-bin": "",
  "grpc-status-details-bin": "\b\r\u0012\u001bInternal error encountered.\u001aE\nCtype.googleapis.com/google.ads.googleads.v5.errors.GoogleAdsFailure",
  "request-id": "QDP5N1nBn8Sf-EWRLR4HwQ"
}
Fault: {
  "created": "@1618586353.715000000",
  "description": "Error received from peer ipv4:142.250.74.42:443",
  "file": "src/core/lib/surface/call.cc",
  "file_line": 1068,
  "grpc_message": "Internal error encountered.",
  "grpc_status": 13
}

[2021-04-16 17:19:13,716 - WARNING] Request made: ClientCustomerId: 9053560327, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v5.services.GoogleAdsService/Search, RequestId: QDP5N1nBn8Sf-EWRLR4HwQ, IsFault: True, FaultMessage: Internal error encountered.
17:19 [Italy24MX]: Encountered unexpected Error

**Comment by xtry** [comment] 2021-07-21 08:15
is there any solution to this issue?

**Comment by skiwan** [comment] 2021-07-21 08:24
@xtry So far Im running into the error again from time to time
Only adivce I can give is to use the latest api version and than send full request logs to google ads support

at googleadsapi-support@google.com
