### ISSUE TITLE
Pip install google-ads is not installing all dependent python libraries

### ISSUE THREAD

**Issue by vinodkumarpk** [googleads/google-ads-python#96] opened 2019-05-03 14:00 UTC
We are in the process of switching over from google adwords api to google ads api python client library for two reasons

1. Need geo performance report which is not available in AdWords api
2. AdWords api sunset by end of 2019

We installed the google-ads python library using pip install google-ads but this is not installing all the dependent python libraries (such as api-core, etc) please provide instructions to install google-ads along with all dependent python libraries.

Thanks,
Vinod

**Comment by BenRKarl** [comment] 2019-05-06 23:56
@vinodkumarpk thanks for posting this question! Can you clarify what command you're running? And are you using a virtual env? What happens when you run:

```bash
pip install google-ads
```

Then:

```bash
pip freeze
```

**Comment by vinodkumarpk** [comment] 2019-05-07 02:41
Hi,

I installed google-ads (using instructions provided in
https://github.com/googleads/google-ads-python/) python library on ubuntu
virtual box.

*IMPORTANT: The documentation for using the python libraries is not clear.
Please provide documentation with steps on what all python libraries need
to be imported along with some good easy to understand sample python code.*


*[vinod@localhost ~]$ pip freeze | grep google*

DEPRECATION: Python 2.7 will reach the end of its life on January 1st,
2020. Please upgrade your Python as Python 2.7 won't be maintained after
that date. A future version of pip will drop support for Python 2.7.

*google*-ads==2.0.0

*google*-api-core==1.10.0

*google*-api-python-client==1.7.8

*google*-auth==1.6.3

*google*-auth-httplib2==0.0.3

*google*-auth-oauthlib==0.3.0

*google*apis-common-protos==1.5.10


*[vinod@localhost ~]$ python --version*

Python 2.7.13



*My Code*

import google.ads.google_ads.client


def main(client, account_id, date):

    print account_id

    print date


if __name__ == '__main__':

    g_verbose = True


    parser = OptionParser()

    parser.add_option("-d", action="store", dest="date")

    parser.add_option("-a", action="store", dest="account_id")


    (options, args) = parser.parse_args(sys.argv[1:])

    # Initialize client object.


    path = '/home/vinod/google_ads/google_ads/google-ads.yaml'


    client =
google.ads.google_ads.client.GoogleAdsClient.load_from_storage(path=path)


    try:

        main(client, options.account_id, options.date)


    except RuntimeError, err:

        print err




*Error*


[vinod@localhost google_ads]$ python google_geo_performance.py -d 20190501
-a 12345

Traceback (most recent call last):

  File "google_geo_performance.py", line 38, in <module>

    import google.ads.google_ads.client

ImportError: No module named google.ads.google_ads.client

[dbadmin@localhost google_ads]$



Here is another link used for reference :
https://github.com/googleads/google-ads-python/issues/3

**Comment by jesusenlanet** [comment] 2019-05-09 08:37
Hello,

I'm trying to run google-ads (v2.0.0) into GAE in local with dev_appserver.py

I followed all the manuals and I can't make it work inside GAE.

Running get_campaings outside of GAE works well, but when I run the code inside GAE, I got this error:

`return google.ads.google_ads.client.GoogleAdsClient(...)`
`AttributeError: 'module' object has no attribute 'ads'`

I know that google-ads need to be installed with the pip -t option to make it available inside GAE, so I don't know what should be the steps to make it work inside GAE.

Any suggestion or is the same problem explained by @vinodkumarpk ??

Lot of thanks.

**Comment by wihl** [comment] 2019-12-27 03:00
Closing this issue as "cannot reproduce." Feel free to reopen it if you can reproduce it with the latest version of the client library. If so, please specify additional details like platform you are using (e.g. Linux / version, OS X, Windows) and the output from pip freeze.

**Closed by wihl** 2019-12-27 03:00 UTC
