### ISSUE TITLE
AttributeError: Assignment not allowed to repeated field "geo_target_constants" in protocol message objec

### ISSUE THREAD

**Issue by sashanclrp** [googleads/google-ads-python#563] opened 2022-01-12 20:50 UTC
Hello, I'm trying to generate a list of Keywords Ideas using the example on the library -> https://github.com/googleads/google-ads-python/blob/main/examples/planning/generate_keyword_ideas.py

The issue is this:

> AttributeError                            Traceback (most recent call last)
> /tmp/ipykernel_1139/3633436456.py in <module>
>          3 
>          4     try:
> ----> 5         main(
>          6             googleads_client,
>          7             customer_id,
> 
> /tmp/ipykernel_1139/1913281068.py in main(client, customer_id, location_ids, language_id, keyword_texts)
>         27     request.customer_id = customer_id
>         28     request.language = language_rn
> ---> 29     request.geo_target_constants = location_rns
>         30     request.include_adult_keywords = False
>         31     request.keyword_plan_network = keyword_plan_network
> 
> AttributeError: Assignment not allowed to repeated field "geo_target_constants" in protocol message object.
>

Can anyone tell me how i can fix this "Assignment not Allowed to repeated field" error? 

Thanks!

**Comment by iamsaurabhgupt** [comment] 2022-01-14 03:56
I am also facing the same problem, even after facing the exact example

**Comment by sashanclrp** [comment] 2022-01-18 18:32
I think I solve the issue! Its basically just a matter of verifying that you have the Following libraries installed

`from google.ads.googleads.errors import GoogleAdsException
from google.ads.googleads.client import GoogleAdsClient # The new Library is googleads not google-ads
import argparse
import sys`

Let me know if this worked for you, before closing the Issue

**Comment by babinos87** [comment] 2022-01-19 14:42
I am getting a very similar error when trying this example: https://developers.google.com/google-ads/api/docs/samples/add-customer-match-user-list.

It fails on this line:
```
request.operations = _build_offline_user_data_job_operations(client)
```
with this error:
```
AttributeError: Assignment not allowed to repeated field "operations" in protocol message object.
```

I am importing the correct client:
```
...
from google.ads.googleads.client import GoogleAdsClient
...
```

I am using version 14.1.0 and I am using `use_proto_plus = False`. I mention the later because I noticed that some other examples are failing, but work when setting this to `True`, so I think those examples are old and work with `use_proto_plus = True`, mainly. Not sure how this can be fixed here or even what the issue is :(

**Comment by BenRKarl** [comment] 2022-01-27 18:39
@babinos87 you're exactly right, this is an issue cause by differences in the two interfaces that you can switch between using the `use_proto_plus` configuration flag. When set to `True` you can assign to repeated fields, and when set to `False` you cannot. Thanks for sharing that documentation, it should include all the necessary context to resolve this problem.

**Closed by BenRKarl** 2022-01-27 18:39 UTC
Labels: question

**Comment by techperfect** [comment] 2022-02-09 08:41
The simplest solution is
request.geo_target_constants.extend(location_rns)
