### ISSUE TITLE
Fetching RSA from SearchStream getting stuck.

### ISSUE THREAD

**Issue by abhiashu** [googleads/google-ads-python#712] opened 2022-10-21 17:51 UTC
**Describe the bug:**
Hi, we are trying to fetch Responsive Search Ads for around 2600 campaigns for a customer by Google Ads API's SearchStream using python client. The total RSA count to be fetched after adding the relevant filters(eg status!=REMOVED) is around 2.6 lakhs.
Issue - When we pull data without RSA fields(eg - ad_group_ad.ad.responsive_search_ad.headlines,ad_group_ad.ad.responsive_search_ad.descriptions, ad_group_ad.ad.responsive_search_ad.path1,ad_group_ad.ad.responsive_search_ad.path2), the code runs fine and data fetch is completed within a minute.
But if we run the same query with RSA related fields, it gets stuck after fetching around 11-14 batches(1.1-1.4 lakh RSA).
Here is the query with RSA fields-
SELECT
campaign.id,ad_group.id,ad_group_ad.ad.id,ad_group_ad.ad.type,campaign.status,ad_group_ad.ad.text_ad.headline,ad_group.status,ad_group_ad.status,
ad_group_ad.ad.text_ad.description1,ad_group_ad.ad.text_ad.description2,ad_group_ad.ad.display_url,ad_group_ad.policy_summary.approval_status,ad_group_ad.ad.device_preference,
ad_group_ad.ad.tracking_url_template,ad_group_ad.ad.final_urls,ad_group_ad.ad.url_custom_parameters,campaign.name,ad_group.name,ad_group_ad.ad.final_url_suffix,
ad_group_ad.ad.text_ad.description1,ad_group_ad.ad_strength,ad_group_ad.ad.responsive_search_ad.headlines,ad_group_ad.ad.responsive_search_ad.descriptions,
ad_group_ad.ad.responsive_search_ad.path1,ad_group_ad.ad.responsive_search_ad.path2
FROM ad_group_ad
WHERE 
campaign.id IN (<2637 campaignids>)
and ad_group_ad.status != REMOVED
and ad_group.status != REMOVED
and campaign.status != REMOVED
and ad_group_ad.ad.type = 'RESPONSIVE_SEARCH_AD';

After remaining stuck for several hours(some times even only few minutes), it gives Stream Removed Error-

grpc._channel._SingleThreadedRendezvous: <_SingleThreadedRendezvous of RPC that terminated with:
      status = StatusCode.UNKNOWN
      details = "Stream removed"
      debug_error_string = "UNKNOWN:Error received from peer ipv4:142.250.77.138:443 {created_time:"2022-10-14T15:49:21.359623+05:30", grpc_status:2, grpc_message:"Stream removed"}

**Steps to Reproduce:**
Try with some same number of campaigns having similar number of RSA's in them for some test account.
**Expected behavior:**
Expectation is that it should get completed with or without RSA fields in the select clause of the query.
**Client library version and API version:**
Client library version: 18.1.0
Google Ads API version: Tried with both v10 and v11

cachetools==5.2.0
certifi==2022.9.24
charset-normalizer==2.1.1
google-ads==18.1.0
google-api-core==2.10.2
google-auth==2.12.0
google-auth-oauthlib==0.5.3
googleapis-common-protos==1.56.4
grpcio==1.49.1
grpcio-status==1.49.1
idna==3.4
oauthlib==3.2.1
proto-plus==1.22.0
protobuf==4.21.7
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyYAML==6.0
requests==2.28.1
requests-oauthlib==1.3.1
rsa==4.9
six==1.16.0
urllib3==1.26.12
**Request/Response Logs:**

 
**Anything else we should know about your project / environment:**
Once I observed this error too, adding for reference-
grpc._channel._SingleThreadedRendezvous: <_SingleThreadedRendezvous of RPC that terminated with:
      status = StatusCode.INTERNAL
      details = "Received RST_STREAM with error code 2"
      debug_error_string = "UNKNOWN:Error received from peer ipv4:142.250.182.42:443 {created_time:"2022-10-14T13:12:08.486828+05:30", grpc_status:13, grpc_message:"Received RST_STREAM with error code 2"}"

Please look into the issue and let me know if any further information is required from my side.

Thanks,
Abhishek Chaturvedi

**Comment by bobhancockg** [comment] 2022-10-21 18:42
How much time has elapsed from the time you send the request until this error occurs?

The grpc error indicates that the termination occurred on the server side, so it may not be library specific.

You say, "After remaining stuck for several hours(some times even only few minutes), it gives Stream Removed Error-". In your best estimation:

- Is there consistency in the amount of time that has elapsed before this occurs? For example, 80% of the time it fails after N hours and 20% of the time it fails after X minutes.
- Is there any correlation between failure and the number of campaign ids in the query?
- Does the query in this issue consistently produce this error?

In order to reproduce this, I'll need to have a hypothesis as to whether it is a function of time, request size, or both.

**Comment by abhiashu** [comment] 2022-10-23 18:43
Hi @bobhancockg,

Addressing your questions below -

How much time has elapsed from the time you send the request until this error occurs?
I re-ran the code snippet again several times, observed that it is giving Stream Not Found error after an hour. Earlier also I had observed this error after an hour(only once or twice in minutes).

The grpc error indicates that the termination occurred on the server side, so it may not be library specific.
I had communicated this issue with the google Ads API cupport team, they tried same request with java client and it did not give any error. They told that they were not able to reproduce the issue. However, they also informed that the API request and responses had large message sizes.

Is there consistency in the amount of time that has elapsed before this occurs? For example, 80% of the time it fails after N hours and 20% of the time it fails after X minutes.
Around 95% time -> After an hour
Around 5% time -> within few minutes(observed only once or twice)

Is there any correlation between failure and the number of campaign ids in the query?
Yes, we tried with lesser campaignids in the query(batches of 200) and it worked.

Does the query in this issue consistently produce this error?
Yes, each time I run this query, it gets stuck after fetching some 1.1-1.4 lakh records(sometimes this number can be 90 thousand also)

**Comment by bobhancockg** [comment] 2022-10-24 12:54
Thanks, this is very useful. I'm going to contact the server side team and
will report back.

I think the best workaround until we find the root of the problem is to use
multiple queries that will execute in < 60 minutes.
Bob Hancock | Google Ads API DevRel | ***@***.*** | 646-727-0741

**Comment by abhiashu** [comment] 2022-12-05 04:05
Hi @bobhancockg please update if there is any, regarding this issue..

**Comment by BenRKarl** [comment] 2023-01-20 18:08
@abhiashu just wanted to check whether you're still having this issue, if so I will jump in to try to help push the investigation forward. Thanks!

**Comment by abhiashu** [comment] 2023-01-27 03:47
@bobhancockg sure, i will try to fetch again and let you know

**Comment by BenRKarl** [comment] 2023-02-02 15:17
@abhiashu just checking in on whether you were able to reproduce this. If not I'll close this issue out. Thanks!

**Comment by abhiashu** [comment] 2023-02-03 03:46
@bobhancockg please wait, i am checking, will let you till EOD

**Comment by abhiashu** [comment] 2023-02-03 09:31
@bobhancockg I am still facing same issue, tried woth both v11 and v12

**Comment by BenRKarl** [comment] 2023-02-24 15:36
@abhiashu apologies for the delayed response. Would you mind summarizing this issue in the [support forum](https://developers.google.com/google-ads/api/support) and requesting help there? This appears to be an issue with the API and not this library, so the forum is better equipped to help with this.

**Closed by BenRKarl** 2023-02-24 15:36 UTC
Labels: bug, triage
