### ISSUE TITLE
OfflineUserDataJobOperation instantiation prohibitively slow

### ISSUE THREAD

**Issue by brianhama** [googleads/google-ads-python#455] opened 2021-06-25 16:30 UTC
**Describe the bug:**

Creating OfflineUserDataJobOperation within a loop, like you would when creating a Customer Match User List, is prohibitively slow. Roughly 5 OfflineUserDataJobOperation objects are created per second. This means that uploading a Customer Match User List with millions of users would take days to complete. The exact same code using the other Google Ad SDKs does not exhibit this behavior.

**Steps to Reproduce:**

```
while index < 100000:
    user_data_operation = OfflineUserDataJobOperation()
    user_data = ( user_data_operation.create )
    user_identifier = UserIdentifier()
    user_identifier.mobile_id = str(uuid.uuid4())
    user_data.user_identifiers.append(user_identifier)
    customer_data_operations.append(user_data_operation)
    index = index + 1
```

**Expected behavior:**

On the other Google Ads SDKs the code above completes instantly. On this Python SDK it takes hours.

**Client library version and API version:**
Client library version: 9.0.0
Google Ads API version: v8

**Request/Response Logs:**
None
 
**Anything else we should know about your project / environment:**
None

**Comment by laurachevalier4** [comment] 2021-06-25 20:30
Hey @brianhama. Is the performance you describe ("Roughly 5 OfflineUserDataJobOperation .. created per second") based on just the snippet you pasted, or are you saying that the request itself (not pasted) completed at that rate? 
Can you give any more details about the environment in which you are running the program (e.g. OS Platform and Distribution, Python version, etc.)?

**Comment by brianhama** [comment] 2021-06-25 20:56
Just the snippet itself, involving no http requests. The snippet I pasted actually runs somewhat faster (about 100 per second) because I deviated from the documentation and instantiated directly OfflineUserDataJobOperation without using the client.get_type() function. If you use that function, it runs even slower (about 5 per second).

I'm only discussing the performance while instantiating the operations in memory. This issue has nothing to do with any http requests.

I've tried running this on both Windows 10 w/ Python 3.8 and the "python:3.8-slim" linux docker image.

**Comment by brianhama** [comment] 2021-06-25 20:58
Here's a video showing the snippet running with the Python SDK: 

https://user-images.githubusercontent.com/1214153/123484528-56feb380-d5bd-11eb-83a0-b7ac6748f0d5.mp4

And here is the same snippet running with the C# SDK:

https://user-images.githubusercontent.com/1214153/123484569-6b42b080-d5bd-11eb-8cc6-87182e75142a.mp4

**Comment by BenRKarl** [comment] 2021-06-30 15:27
@brianhama could you share the full script you're using? I put the below together and it completed in 1125ms, similar to how the C# script performs in the above video. Are there any differences here that might account for the slowness?

```py
import time
import uuid

from google.ads.google_ads.v6.proto.services.offline_user_data_job_service_pb2 import OfflineUserDataJobOperation
from google.ads.google_ads.v6.proto.common.offline_user_data_pb2 import UserIdentifier

time_total = 0
index = 0
customer_data_operations = []
while index < 100000:
    start = time.time()
    user_data_operation = OfflineUserDataJobOperation()
    user_data = ( user_data_operation.create )
    user_identifier = UserIdentifier()
    user_identifier.mobile_id = str(uuid.uuid4())
    user_data.user_identifiers.append(user_identifier)
    customer_data_operations.append(user_data_operation)
    print(f"{index}")
    index = index + 1
    time_total = time_total + (time.time() - start)

print(f"Total time: {time_total * 1000}")
```

**Comment by brianhama** [comment] 2021-07-02 16:22
I was importing from a different namespace:

```
from google.ads.googleads.v8.services.types.offline_user_data_job_service import OfflineUserDataJobOperation
from google.ads.googleads.v8.common.types.offline_user_data import UserIdentifier
```

Could that be relevant? Other than that, my script looks identical to yours.

**Comment by brianhama** [comment] 2021-07-02 16:28
I tried running your script and the modules you are importing couldn't be found. I have the latest version (12.0.0) of the SDK.

**Comment by BenRKarl** [comment] 2021-07-07 17:05
@brianhama if you're using version 12.0.0 of this library and `v8` of the Google Ads API the script is slightly different because the module paths changed with [version 10.0.0](https://developers.google.com/google-ads/api/docs/client-libs/python/library-version-10) of this library. Note, below only the import paths are different, all the rest is the same as my last post.

```py
import time
import uuid

from google.ads.googleads.v8.services.types.offline_user_data_job_service import OfflineUserDataJobOperation
from google.ads.googleads.v8.common.types.offline_user_data import UserIdentifier

time_total = 0
index = 0
customer_data_operations = []
while index < 100000:
    start = time.time()
    user_data_operation = OfflineUserDataJobOperation()
    user_data = ( user_data_operation.create )
    user_identifier = UserIdentifier()
    user_identifier.mobile_id = str(uuid.uuid4())
    user_data.user_identifiers.append(user_identifier)
    customer_data_operations.append(user_data_operation)
    print(f"{index}")
    index = index + 1
    time_total = time_total + (time.time() - start)

print(f"Total time: {time_total * 1000}")
```

This executes slightly slower, which is expected, but still completes in ~3.4 seconds. Let me know if you get different results.

**Comment by brianhama** [comment] 2021-07-09 20:06
@BenRKarl I don't know how long 100K would take to execute, but 1,000 takes over 17 seconds for me to execute:

![image](https://user-images.githubusercontent.com/1214153/125130727-53d3ef00-e0b6-11eb-90a3-de87925074e2.png)

I'm running Python 3.8.8 64-bit, but I've replicated on multiple systems. What other information could I provide to help you debug?

**Comment by BenRKarl** [comment] 2021-07-12 14:30
@brianhama I get roughly the same results with Python 3.8.8 locally, ~3.6 seconds. You're using Windows 10, right? And running other environments (i.e. Linux) via Docker containers?

**Comment by brianhama** [comment] 2021-07-13 17:42
@BenRKarl Yes, but I am not running Docker on Windows 10. I am running Docker in AWS using the python:3.8-slim base image.

**Comment by BenRKarl** [comment] 2021-07-13 18:04
@brianhama gotcha - so you're getting the same results whether it's running _locally_ on Windows 10 or via Docker in AWS? Or are your Windows tests also running in AWS? I had a colleague test the above script in their Windows environment and they processed 100k loops in roughly 13 seconds, so I'm quite unsure what's causing the slowness for you. My best guess at this point is a difference in compute power - what specs does the AWS environment have that you're using?

**Comment by BenRKarl** [comment] 2021-07-13 18:07
@brianhama also are you doing any multiprocessing when running this script? I'm curious if there are other aspects of your application that could be a clue.

**Comment by brianhama** [comment] 2021-07-15 17:32
I'm running just the script that you provided. Nothing strange going on at all.

**Comment by BenRKarl** [comment] 2021-07-26 16:02
@brianhama ok - can you share more specific details about the Linux environment where you're seeing the regression? Also the results of `pip freeze`? So far we haven't been able to reproduce this so it's hard to diagnose the problem.

**Comment by BenRKarl** [comment] 2021-08-10 13:47
I'm going to close this out because we can't reproduce it, but please feel free to reopen with any additional details.

**Closed by BenRKarl** 2021-08-10 13:47 UTC
Labels: bug, triage
