### ISSUE TITLE
"No status received" with 100 operations for MutateAdGroupAds

### ISSUE THREAD

**Issue by MarTango** [googleads/google-ads-python#38] opened 2019-02-20 12:20 UTC
I'm getting a "No status received" grpc response (see below), when calling:

```python
service = client.get_service("AdGroupAdService")
resp = service.mutate_ad_group_ads(customer_id, operations) # len(operations) == 100
```

I believe that I can get a proper response if I send fewer operations (around 10? untested).
However, since the API should be able to handle 5000 operations at a time, I think this is an issue that should be flagged.

An element in `operations` above looks like

`google.ads.googleads_v0.types.AdGroupAdOperation`
```
create {
  ad_group {
    value: "customers/{redacted}/adGroups/{redacted}"
  }
  ad {
    final_urls {
      value: "https://redacted.com"
    }
    display_url {
    }
    expanded_text_ad {
      headline_part1 {
        value: "redacted"
      }
      headline_part2 {
        value: "redacted"
      }
      description {
        value: "redcated"
      }
      description2 {
        value: "redacted"
      }
    }
  }
}
```

## Traceback
```
WARNING:google.ads.google_ads.client:Request made: ClientCustomerId: [REDACTED], Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v0.services.AdGroupAdService/MutateAdGroupAds, RequestId: None, IsFault: True, FaultMessage: No status received
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/grpc/_interceptor.py", line 215, in __call__
    wait_for_ready=wait_for_ready)
  File "/usr/local/lib/python3.7/site-packages/grpc/_interceptor.py", line 245, in _with_call
    return call.result(), call
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 295, in result
    raise self
  File "/usr/local/lib/python3.7/site-packages/grpc/_interceptor.py", line 236, in continuation
    wait_for_ready=new_wait_for_ready)
  File "/usr/local/lib/python3.7/site-packages/grpc/_interceptor.py", line 258, in with_call
    wait_for_ready=wait_for_ready)
  File "/usr/local/lib/python3.7/site-packages/grpc/_interceptor.py", line 245, in _with_call
    return call.result(), call
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 295, in result
    raise self
  File "/usr/local/lib/python3.7/site-packages/grpc/_interceptor.py", line 236, in continuation
    wait_for_ready=new_wait_for_ready)
  File "/usr/local/lib/python3.7/site-packages/grpc/_interceptor.py", line 258, in with_call
    wait_for_ready=wait_for_ready)
  File "/usr/local/lib/python3.7/site-packages/grpc/_interceptor.py", line 244, in _with_call
    continuation, client_call_details, request)
  File "/usr/local/lib/python3.7/site-packages/google/ads/google_ads/client.py", line 335, in intercept_unary_unary
    self._handle_grpc_failure(response)
  File "/usr/local/lib/python3.7/site-packages/google/ads/google_ads/client.py", line 310, in _handle_grpc_failure
    raise exception
  File "/usr/local/lib/python3.7/site-packages/grpc/_interceptor.py", line 236, in continuation
    wait_for_ready=new_wait_for_ready)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 560, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "No status received"
	debug_error_string = "{"created":"@1550664734.372858800","description":"No status received","file":"src/core/lib/surface/call.cc","file_line":1058,"grpc_status":2}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/google/ads/google_ads/v0/services/ad_group_ad_service_client.py", line 278, in mutate_ad_group_ads
    request, retry=retry, timeout=timeout, metadata=metadata)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 270, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 179, in retry_target
    return target()
  File "/usr/local/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.Unknown: None No status received
```

**Comment by MarTango** [comment] 2019-02-20 12:24
- If I send 50 operations, it works.
- If I send 63 operations, I get `{"created":"@1550665358.548415000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"received trailing metadata size exceeds limit","grpc_status":8}"`
- If I send 75, I get `No status received`

**Comment by BenRKarl** [comment] 2019-02-21 00:34
Hi @MarTango thanks for sending along all of this information! My suspicion is that this may be caused by some temporary limitations due to the API being in beta, but I will look into it further just to make sure.

**Comment by MarTango** [comment] 2019-02-21 09:27
Thanks Ben, it does seem likely that that's the case.

When does the API exit beta?

**Comment by BenRKarl** [comment] 2019-03-20 12:47
Hi @MarTango the API left beta with the release of v1. Have you been able to upgrade to v1, and if so are you continuing to have these issues?

**Comment by MarTango** [comment] 2019-03-20 13:36
@BenRKarl I have upgraded to v1, but unfortunately I'm still experiencing these issues.

**Comment by BenRKarl** [comment] 2019-03-21 21:08
@MarTango It's possible you might be hitting [this issue](https://github.com/grpc/grpc/issues/7927) where payload size is limited to 4MB at the gRPC level. That would make sense given that your errors are reproducible based on the number of operations sent. If it were an issue of server capacity I'd expect the errors to be less predictable. We're considering options to address this issue as 4MB might be too low, but I'm not sure what the resolution will be. In the meantime I'm afraid you may just need to tune your requests to be under the threshold.

**Comment by MarTango** [comment] 2019-03-21 22:59
Thanks @BenRKarl, do you know if there's a way to estimate the size of the payload from a list of operations?

**Comment by BenRKarl** [comment] 2019-03-22 12:25
@MarTango it's possible to read the byte length of a request, however this isn't currently exposed in the library. For background, in the interceptors ([here](https://github.com/googleads/google-ads-python/blob/master/google/ads/google_ads/client.py#L590) for example) the `request` object has a `ByteLength` method.

I'm going to convert this Issue to a feature request and see if we can add this value to the logs so that it's always printed for easy reference.

The downside however is we won't be able to know the size of the response payload.

**Comment by BenRKarl** [comment] 2019-03-22 12:56
@MarTango just to add on there for clarify. The specific issue here doesn't seem to be the size of the request payload, although there do appear to be limits on that, it appears to be the size of the trailing metadata in the response. Some of the operations being sent may be generating errors of some kind, which are sent in the metadata and can cause it to be quite large. So the issue is related to both request and response sizes of the body and metadata.

**Comment by BenRKarl** [comment] 2019-05-10 14:14
Closing this, since the original error was related to the size of trailing_metadata and not request size, which hasn't been an issue.

**Closed by BenRKarl** 2019-05-10 14:14 UTC
Labels: enhancement
