### ISSUE TITLE
Should GoogleAdsClient initialization refresh token?

### ISSUE THREAD

**Issue by jwygoda** [googleads/google-ads-python#289] opened 2020-07-14 17:57 UTC
[Optimizing OAuth Requests](https://developers.google.com/google-ads/api/docs/oauth/optimizing-requests#refresh_job) states that users should setup a refresh job that periodically refreshes the credential and stores it in the data store. Isn't [this line](https://github.com/googleads/google-ads-python/blob/ca3f821e011455a9fba74fc054e4ca2de7121562/google/ads/google_ads/oauth2.py#L38) in contrary with this recommendation? It [refreshes token grant](https://github.com/googleapis/google-auth-library-python/blob/9058f1fea680613d9717a62ee37dc294c11b9c8a/google/oauth2/_client.py#L207) on every GoogleAdsClient initialization which is not particularly efficient. Could you make it configurable in config so that we can switch to manual refresh?

**Comment by BenRKarl** [comment] 2021-03-31 18:19
@jwygoda I'm going to mark this as a duplicate of #6, which is a feature request to add an option to cache access tokens so that the round trip isn't necessary on client initialization. 

Also I believe that the [Optimizing OAuth Requests](https://developers.google.com/google-ads/api/docs/oauth/optimizing-requests#refresh_job) section was removed as it's not a recommended best practice for the Google Ads API.

**Closed by BenRKarl** 2021-03-31 18:19 UTC
