### ISSUE TITLE
Listing group referenced in the operation was not found in the ad group

### ISSUE THREAD

**Issue by deepakinfoweb** [googleads/google-ads-python#502] opened 2021-09-23 04:56 UTC
We have also added **parent_ad_group_criterion**  in the request. Still, We are getting the error The required field was not present.

Request input json :
[{"create": {
        "resource_name": "customers/7370860149/adGroupCriteria/125570209334~-1",
        "status": "ENABLED",
        "listing_group": {
            "type_": "UNIT",
            "case_value": {
                "product_item_id": {
                    "value": "4309645"
                }
            },
            "parent_ad_group_criterion": "customers/7370860149/adGroupCriteria/125570209334~-1"
        }
    }}]

Response : 

Request made: ClientCustomerId: 7370860149, Host: googleads.googleapis.com, Method: /google.ads.googleads.v8.services.AdGroupCriterionService/MutateAdGroupCriteria, RequestId: ML0n3nvxfc6VX1TNxmoTcA, IsFault: True, FaultMessage: Listing group referenced in the operation was not found in the ad group.
Request with ID 'ML0n3nvxfc6VX1TNxmoTcA' failed with status 'INVALID_ARGUMENT' and includes the following errors:
        Error with message 'Listing group referenced in the operation was not found in the ad group.'.
                On field: operations
                On field: create
                On field: listing_group
                On field: parent_ad_group_criterion

**Comment by BenRKarl** [comment] 2021-09-27 14:33
Closing as a duplicate of #501

**Closed by BenRKarl** 2021-09-27 14:33 UTC
Labels: bug, triage
