### ISSUE TITLE
InternalError when running add_customer_match_user_list.py example

### ISSUE THREAD

**Issue by germad** [googleads/google-ads-python#378] opened 2021-01-26 12:46 UTC
Running an [Example](https://github.com/googleads/google-ads-python/blob/master/examples/remarketing/add_customer_match_user_list.py) showing creation of customer match UserList produces the following output (UserList is successully created, but OfflineUserDataJob does not end successfully):

```
User list with resource name 'customers/{customer_id}/userLists/6562749814' was created.
Created an offline user data job with resource name: 'customers/{customer_id}/offlineUserDataJobs/4691406091'.
The operations are added to the offline user data job.
Request to execute the added operations started.
Waiting until operation completes...
Request made: ClientCustomerId: None, Host: googleads.googleapis.com:443, Method: /google.longrunning.Operations/GetOperation, RequestId: x73gqu0icxrYbHwoVXNeww, IsFault: True, FaultMessage: Internal error encountered.
Request made: ClientCustomerId: None, Host: googleads.googleapis.com:443, Method: /google.longrunning.Operations/GetOperation, RequestId: vQw1qkfMJVGj1axuzFot2g, IsFault: True, FaultMessage: Internal error encountered.
...
```
The process hangs and keeps working indefinitely.

**Comment by stephenjwz** [comment] 2021-03-01 13:24
I am also experiencing this. From discussion on the google group, maybe similar to https://github.com/googleads/google-ads-java/issues/402 ?

**Comment by nwbirnie** [comment] 2021-03-03 13:36
Friendly ping - please fix this when you've got a sec.

**Comment by BenRKarl** [comment] 2021-03-03 15:07
@stephenjwz I'm not sure this is the same issue as in the Java library since the fix there was to add the call to run the job, which is already present in this example.

I'm looking into the issue, but don't think it's as simple as it was for Java.

**Comment by BenRKarl** [comment] 2021-03-04 16:21
Hi all - I think the issue here is that creating these user lists just does take a lot of time, note that in the Java example there's a [comment](https://github.com/googleads/google-ads-java/blob/master/google-ads-examples/src/main/java/com/google/ads/googleads/examples/remarketing/AddCustomerMatchUserList.java#L239) explaining that the process can take up to 24 hours. 

Another way to check the status of the list is to use a query, [like they do in Java](https://github.com/googleads/google-ads-java/blob/master/google-ads-examples/src/main/java/com/google/ads/googleads/examples/remarketing/AddCustomerMatchUserList.java#L334), to check for jobs with status `RUNNING`.

When I test this example I have a similar experience, the process pings for completion for a very long time, if I kill it and submit a search query similar to the linked one I can see the lists in a `RUNNING` state.

So this appears to be working as intended. I'm going to close this for now, but if you think there's another problem feel free to reopen it.

**Comment by stephenjwz** [comment] 2021-03-04 17:57
Hi Ben

This makes sense - it's not unexpected for the process of updating a list to take a day or so, based on previous experiences with adwords.

As I'm not much of a python/google api expert, I am drawing on https://github.com/googleads/google-ads-python/blob/master/examples/remarketing/add_customer_match_user_list.py from the supplied examples as a basis for how to update lists. Would it be possible to update that or share an example which does not wait ~24h for this stuff to complete?
Am I right in thinking it should be as simple as removing line 189 or would there be more to it than that?

Thanks

Stephen

**Comment by BenRKarl** [comment] 2021-03-04 18:15
@stephenjwz that's a great suggestion, I'll turn this into a feature request for us to structure this example more like the Java one, so that it's clear how to proceed without needing to wait for the LRO to complete.

**Comment by Robin-Sky** [comment] 2021-03-09 08:43
Thanks @BenRKarl .
I work with @stephenjwz , we had to pause all our media campaigns with Google until we are able to refresh our audience segments.

Do you have a rough timelines for providing the instructions above?    (So I can manage expectations with our media planners / programmatic team on when we may be able to restart our campaigns)

**Comment by BenRKarl** [comment] 2021-03-09 15:48
@Robin-Sky I'm working on an update today, I expect to at least have a PR ready, at which point I'll like it here so you can see the changes.

**Closed** 2021-03-10 19:21 UTC
Labels: code example, enhancement
