### ISSUE TITLE
Cannot check peer: missing selected ALPN property

### ISSUE THREAD

**Issue by shireresident** [googleads/google-ads-python#411] opened 2021-04-22 11:44 UTC
I am using the google-ads python package 10.0.0 with Python 3.8 on RHEL7 with openssl version 1.0.2k-fips.

When I try to access any functionality I get this error when I turn GRPC debug on.

`D0421 16:57:15.427572080   23420 security_handshaker.cc:183] Security handshake failed: {"created":"@1619038635.427538310","description":"Cannot check peer: missing selected ALPN property.","file":"src/core/lib/security/security_connector/ssl_utils.cc","file_line":161}`

I am operating in a corporate setting that intercepts all external communication and inserts its own certificates.

It works fine on my local Windows 10 desktop that is also in the same corporate setting.

**Comment by BenRKarl** [comment] 2021-04-22 12:50
Hi @shireresident seems this is a duplicate of [this existing issue](https://github.com/grpc/grpc/issues/23172) on gRPC. Would you mind chiming in on that thread with your own details so that they can identify the issue? I'll follow along and keep this issue open just in case others are running into this problem.

**Comment by shireresident** [comment] 2021-04-22 12:54
Will follow there. Thanks @BenRKarl.

**Comment by BenRKarl** [comment] 2021-05-06 17:03
@shireresident are you able to work around this error using the solution described in [this comment](https://github.com/grpc/grpc/issues/23172#issuecomment-833509868)? If so I'd like to close this issue, since the problem is in a separate library. Once it gets fixed in gRPC this library will pick up the changes in the subsequent release.

**Comment by shireresident** [comment] 2021-05-06 17:18
@BenRKarl My issue seems to be unrelated to that. Our issue was our corporate firewall was terminating the SSL and initiating a new one. It was likely forcing HTTP 1.1 and dropping the ALPN. We implemented a firewall change last night to skip the SSL bridging for our IP and it is working fine now. You may close the issue.

Apparently when I use windows it was going with TLS 1.3 that are firewall was passing through and hence it was working on Windows.

**Comment by BenRKarl** [comment] 2021-05-06 17:22
@shireresident thanks for sharing the explanation, hopefully if anyone else runs into this issue these details will be helpful.

**Closed by BenRKarl** 2021-05-06 17:22 UTC
Labels: bug
