### ISSUE TITLE
TypeError: Invalid constructor input for SearchGoogleAdsRequest

### ISSUE THREAD

**Issue by maximbogan** [googleads/google-ads-python#479] opened 2021-08-10 13:22 UTC
python: 3.8

snippet:

test request:
```
query = f"""
SELECT
change_event.change_date_time
FROM change_event
WHERE
change_event.change_date_time DURING LAST_7_DAYS
LIMIT 10
"""
search_request = self.client.get_type("SearchGoogleAdsRequest")
search_request.customer_id = customer_id
search_request.query = query
search_request.page_size = 10
results = self.ga_service.search(request=search_request)
```
real request:
```

query = f"""
        SELECT
      customer.descriptive_name,
      change_event.campaign,
      campaign.id,
      campaign.name,
      change_event.resource_name,
      change_event.change_date_time,
      change_event.change_resource_name,
      change_event.user_email,
      change_event.client_type,
      change_event.change_resource_type,
      change_event.old_resource,
      change_event.new_resource,
      change_event.resource_change_operation,
      change_event.changed_fields
    FROM change_event
    WHERE change_event.change_date_time < '{yesterday}'
    AND change_event.change_date_time >= '{weeks_ago}'
    ORDER BY change_event.change_date_time DESC
    LIMIT 10000
    """

search_request = self.client.get_type("SearchGoogleAdsRequest")
search_request.customer_id = customer_id
search_request.query = query
search_request.page_size = 10000
```

With google-ads versions:

- 13.0.0
- 12..0.0

I got this error:
```
Traceback (most recent call last):
  File "C:/Users/m.bogan/PycharmProjects/traffic_manager_activity/main.py", line 245, in <module>
    main('request')
  File "C:/Users/m.bogan/PycharmProjects/traffic_manager_activity/main.py", line 222, in main
    mcc_history = mcc_history.append(report.get_change_history_by_customer(str(customer_id)), ignore_index=True)
  File "C:/Users/m.bogan/PycharmProjects/traffic_manager_activity/main.py", line 138, in get_change_history_by_customer
    results = self.ga_service.search(request=search_request)
  File "C:\Users\m.bogan\Anaconda3\envs\traffic_manager_activity\lib\site-packages\google\ads\googleads\v7\services\services\google_ads_service\client.py", line 2637, in search
    request = google_ads_service.SearchGoogleAdsRequest(request)
  File "C:\Users\m.bogan\Anaconda3\envs\traffic_manager_activity\lib\site-packages\proto\message.py", line 494, in __init__
    raise TypeError(
TypeError: Invalid constructor input for SearchGoogleAdsRequest: customer_id: "2057765370"
query: "\n            SELECT\n            change_event.change_date_time\n            FROM change_event\n            WHERE\n            change_event.change_date_time DURING LAST_7_DAYS\n            LIMIT 10\n            "
page_size: 10
```

But with earlier versions google-ads it works well.

Error says that that constructor is invalid.
But [Google Ads Query Builder](https://developers.google.com/google-ads/api/fields/v8/query_validator) says that my query is valid.

**Comment by wihl** [comment] 2021-08-10 19:24
Hi @maximbogan, at first glance, there is nothing wrong with the code snippet you posted. A few questions:

* Was the earlier version of google-ads lower than v10?
* Can you share the results of `pip freeze` or `conda list --export` when using v12 or v13?

Given you are using Windows and Anaconda, please verify that the dependencies have been updated correctly with the new version of google-ads.

**Comment by maximbogan** [comment] 2021-08-11 09:42
Hi,

- The earlier version wasn't lower than v10, it was 11.
- conda list --export:

```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
_ipyw_jlab_nb_ext_conf=0.1.0=py38_0
alabaster=0.7.12=pyhd3eb1b0_0
anaconda-client=1.7.2=py38_0
anaconda-project=0.9.1=pyhd3eb1b0_1
anyio=2.2.0=py38haa95532_2
appdirs=1.4.4=py_0
argcomplete=1.12.3=pypi_0
argh=0.26.2=py38_0
argon2-cffi=20.1.0=py38h2bbff1b_1
asn1crypto=1.4.0=py_0
astroid=2.5=py38haa95532_1
astropy=4.2.1=py38h2bbff1b_1
async_generator=1.10=pyhd3eb1b0_0
atomicwrites=1.4.0=py_0
attrs=20.3.0=pyhd3eb1b0_0
autopep8=1.5.6=pyhd3eb1b0_0
babel=2.9.0=pyhd3eb1b0_0
backcall=0.2.0=pyhd3eb1b0_0
backports=1.0=pyhd3eb1b0_2
backports-entry-points-selectable=1.1.0=pypi_0
backports.functools_lru_cache=1.6.4=pyhd3eb1b0_0
backports.shutil_get_terminal_size=1.0.0=pyhd3eb1b0_3
backports.tempfile=1.0=pyhd3eb1b0_1
backports.weakref=1.0.post1=py_1
bcrypt=3.2.0=py38he774522_0
beautifulsoup4=4.9.3=pyha847dfd_0
bitarray=1.9.2=py38h2bbff1b_1
bkcharts=0.2=py38_0
black=19.10b0=py_0
blas=1.0=mkl
bleach=3.3.0=pyhd3eb1b0_0
blosc=1.21.0=h19a0ad4_0
bokeh=2.3.2=py38haa95532_0
boto=2.49.0=py38_0
bottleneck=1.3.2=py38h2a96729_1
brotli=1.0.9=ha925a31_2
brotlipy=0.7.0=py38h2bbff1b_1003
bzip2=1.0.8=he774522_0
ca-certificates=2021.4.13=haa95532_1
cachetools=4.2.2=pypi_0
certifi=2020.12.5=py38haa95532_0
cffi=1.14.5=py38hcd4344a_0
chardet=4.0.0=py38haa95532_1003
charls=2.2.0=h6c2663c_0
click=7.1.2=pyhd3eb1b0_0
cloudpickle=1.6.0=py_0
clyent=1.2.2=py38_1
colorama=0.4.4=pyhd3eb1b0_0
colorlog=4.8.0=pypi_0
comtypes=1.1.9=py38haa95532_1002
conda-content-trust=0.1.1=pyhd3eb1b0_0
conda-package-handling=1.7.3=py38h8cc25b3_1
conda-repo-cli=1.0.4=pyhd3eb1b0_0
conda-verify=3.4.2=py_1
contextlib2=0.6.0.post1=py_0
cryptography=3.4.7=py38h71e12ea_0
curl=7.71.1=h2a8f88b_1
cycler=0.10.0=py38_0
cython=0.29.23=py38hd77b12b_0
cytoolz=0.11.0=py38he774522_0
dask=2021.4.0=pyhd3eb1b0_0
dask-core=2021.4.0=pyhd3eb1b0_0
decorator=5.0.6=pyhd3eb1b0_0
defusedxml=0.7.1=pyhd3eb1b0_0
diff-match-patch=20200713=py_0
distlib=0.3.2=pypi_0
distributed=2021.4.0=py38haa95532_0
docutils=0.17=py38haa95532_1
entrypoints=0.3=py38_0
et_xmlfile=1.0.1=py_1001
fastcache=1.1.0=py38he774522_0
filelock=3.0.12=pyhd3eb1b0_1
flake8=3.9.0=pyhd3eb1b0_0
flask=1.1.2=pyhd3eb1b0_0
freetype=2.10.4=hd328e21_0
fsspec=0.9.0=pyhd3eb1b0_0
future=0.18.2=py38_1
get_terminal_size=1.0.0=h38e98db_0
gevent=21.1.2=py38h2bbff1b_1
giflib=5.2.1=h62dcd97_0
glob2=0.7=pyhd3eb1b0_0
google-ads=11.0.2=pypi_0
google-api-core=1.31.1=pypi_0
google-api-python-client=2.15.0=pypi_0
google-auth=1.34.0=pypi_0
google-auth-httplib2=0.1.0=pypi_0
google-auth-oauthlib=0.4.5=pypi_0
google-cloud-bigquery=2.23.3=pypi_0
google-cloud-core=1.7.2=pypi_0
google-crc32c=1.1.2=pypi_0
google-resumable-media=1.3.3=pypi_0
googleapis-common-protos=1.53.0=pypi_0
greenlet=1.0.0=py38hd77b12b_2
grpcio=1.39.0=pypi_0
h5py=2.10.0=py38h5e291fa_0
hdf5=1.10.4=h7ebc959_0
heapdict=1.0.1=py_0
html5lib=1.1=py_0
httplib2=0.19.1=pypi_0
icc_rt=2019.0.0=h0cc432a_1
icu=58.2=ha925a31_3
idna=2.10=pyhd3eb1b0_0
imagecodecs=2021.3.31=py38h5da4933_0
imageio=2.9.0=pyhd3eb1b0_0
imagesize=1.2.0=pyhd3eb1b0_0
importlib-metadata=3.10.0=py38haa95532_0
importlib_metadata=3.10.0=hd3eb1b0_0
iniconfig=1.1.1=pyhd3eb1b0_0
intel-openmp=2021.2.0=haa95532_616
intervaltree=3.1.0=py_0
ipykernel=5.3.4=py38h5ca1d4c_0
ipython=7.22.0=py38hd4e2768_0
ipython_genutils=0.2.0=pyhd3eb1b0_1
ipywidgets=7.6.3=pyhd3eb1b0_1
isort=5.8.0=pyhd3eb1b0_0
itsdangerous=1.1.0=pyhd3eb1b0_0
jdcal=1.4.1=py_0
jedi=0.17.2=py38haa95532_1
jinja2=2.11.3=pyhd3eb1b0_0
joblib=1.0.1=pyhd3eb1b0_0
jpeg=9b=hb83a4c4_2
json5=0.9.5=py_0
jsonschema=3.2.0=py_2
jupyter=1.0.0=py38_7
jupyter-packaging=0.7.12=pyhd3eb1b0_0
jupyter_client=6.1.12=pyhd3eb1b0_0
jupyter_console=6.4.0=pyhd3eb1b0_0
jupyter_core=4.7.1=py38haa95532_0
jupyter_server=1.4.1=py38haa95532_0
jupyterlab=3.0.14=pyhd3eb1b0_1
jupyterlab_pygments=0.1.2=py_0
jupyterlab_server=2.4.0=pyhd3eb1b0_0
jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
keyring=22.3.0=py38haa95532_0
kiwisolver=1.3.1=py38hd77b12b_0
krb5=1.18.2=hc04afaa_0
lazy-object-proxy=1.6.0=py38h2bbff1b_0
lcms2=2.12=h83e58a3_0
lerc=2.2.1=hd77b12b_0
libaec=1.0.4=h33f27b4_1
libarchive=3.4.2=h5e25573_0
libcurl=7.71.1=h2a8f88b_1
libdeflate=1.7=h2bbff1b_5
libiconv=1.15=h1df5818_7
liblief=0.10.1=ha925a31_0
libpng=1.6.37=h2a8f88b_0
libsodium=1.0.18=h62dcd97_0
libspatialindex=1.9.3=h6c2663c_0
libssh2=1.9.0=h7a1dbc1_1
libtiff=4.2.0=hd0e1b90_0
libxml2=2.9.10=hb89e7f3_3
libxslt=1.1.34=he774522_0
libzopfli=1.0.3=ha925a31_0
llvmlite=0.36.0=py38h34b8924_4
locket=0.2.1=py38haa95532_1
lxml=4.6.3=py38h9b66d53_0
lz4-c=1.9.3=h2bbff1b_0
lzo=2.10=he774522_2
m2w64-gcc-libgfortran=5.3.0=6
m2w64-gcc-libs=5.3.0=7
m2w64-gcc-libs-core=5.3.0=7
m2w64-gmp=6.1.0=2
m2w64-libwinpthread-git=5.0.0.4634.697f757=2
markupsafe=1.1.1=py38he774522_0
matplotlib=3.3.4=py38haa95532_0
matplotlib-base=3.3.4=py38h49ac443_0
mccabe=0.6.1=py38_1
menuinst=1.4.16=py38he774522_1
mistune=0.8.4=py38he774522_1000
mkl=2021.2.0=haa95532_296
mkl-service=2.3.0=py38h2bbff1b_1
mkl_fft=1.3.0=py38h277e83a_2
mkl_random=1.2.1=py38hf11a4ad_2
mock=4.0.3=pyhd3eb1b0_0
more-itertools=8.7.0=pyhd3eb1b0_0
mpmath=1.2.1=py38haa95532_0
msgpack-python=1.0.2=py38h59b6b97_1
msys2-conda-epoch=20160418=1
multipledispatch=0.6.0=py38_0
mypy_extensions=0.4.3=py38_0
navigator-updater=0.2.1=py38_0
nbclassic=0.2.6=pyhd3eb1b0_0
nbclient=0.5.3=pyhd3eb1b0_0
nbconvert=6.0.7=py38_0
nbformat=5.1.3=pyhd3eb1b0_0
nest-asyncio=1.5.1=pyhd3eb1b0_0
networkx=2.5=py_0
nltk=3.6.1=pyhd3eb1b0_0
nose=1.3.7=pyhd3eb1b0_1006
notebook=6.3.0=py38haa95532_0
nox=2020.12.31=pypi_0
numba=0.53.1=py38hf11a4ad_0
numexpr=2.7.3=py38hb80d3ca_1
numpy=1.20.1=py38h34a8a5c_0
numpy-base=1.20.1=py38haf7ebc8_0
numpydoc=1.1.0=pyhd3eb1b0_1
oauth2client=4.1.3=pypi_0
oauthlib=3.1.1=pypi_0
olefile=0.46=py_0
openjpeg=2.3.0=h5ec785f_1
openpyxl=3.0.7=pyhd3eb1b0_0
openssl=1.1.1k=h2bbff1b_0
packaging=20.9=pyhd3eb1b0_0
pandas=1.2.4=py38hd77b12b_0
pandoc=2.12=haa95532_0
pandocfilters=1.4.3=py38haa95532_1
paramiko=2.7.2=py_0
parso=0.7.0=py_0
partd=1.2.0=pyhd3eb1b0_0
path=15.1.2=py38haa95532_0
path.py=12.5.0=0
pathlib2=2.3.5=py38haa95532_2
pathspec=0.7.0=py_0
patsy=0.5.1=py38_0
pep562=1.1=pypi_0
pep8=1.7.1=py38_0
pexpect=4.8.0=pyhd3eb1b0_3
pickleshare=0.7.5=pyhd3eb1b0_1003
pillow=8.2.0=py38h4fa10fc_0
pip=21.0.1=py38haa95532_0
pkginfo=1.7.0=py38haa95532_0
platformdirs=2.2.0=pypi_0
pluggy=0.13.1=py38haa95532_0
ply=3.11=py38_0
prometheus_client=0.10.1=pyhd3eb1b0_0
prompt-toolkit=3.0.17=pyh06a4308_0
prompt_toolkit=3.0.17=hd3eb1b0_0
proto-plus=1.19.0=pypi_0
protobuf=3.17.3=pypi_0
psutil=5.8.0=py38h2bbff1b_1
ptyprocess=0.7.0=pyhd3eb1b0_2
py=1.10.0=pyhd3eb1b0_0
py-lief=0.10.1=py38ha925a31_0
pyarrow=4.0.1=pypi_0
pyasn1=0.4.8=pypi_0
pyasn1-modules=0.2.8=pypi_0
pycodestyle=2.6.0=pyhd3eb1b0_0
pycosat=0.6.3=py38h2bbff1b_0
pycparser=2.20=py_2
pycurl=7.43.0.6=py38h7a1dbc1_0
pydocstyle=6.0.0=pyhd3eb1b0_0
pyerfa=1.7.3=py38h2bbff1b_0
pyflakes=2.2.0=pyhd3eb1b0_0
pygments=2.8.1=pyhd3eb1b0_0
pylint=2.7.4=py38haa95532_1
pyls-black=0.4.6=hd3eb1b0_0
pyls-spyder=0.3.2=pyhd3eb1b0_0
pynacl=1.4.0=py38h62dcd97_1
pyodbc=4.0.30=py38ha925a31_0
pyopenssl=20.0.1=pyhd3eb1b0_1
pyparsing=2.4.7=pyhd3eb1b0_0
pyqt=5.9.2=py38ha925a31_4
pyreadline=2.1=py38_1
pyrsistent=0.17.3=py38he774522_0
pysocks=1.7.1=py38haa95532_0
pytables=3.6.1=py38ha5be198_0
pytest=6.2.3=py38haa95532_2
python=3.8.8=hdbf39b2_5
python-dateutil=2.8.1=pyhd3eb1b0_0
python-jsonrpc-server=0.4.0=py_0
python-language-server=0.36.2=pyhd3eb1b0_0
python-libarchive-c=2.9=pyhd3eb1b0_1
pytz=2021.1=pyhd3eb1b0_0
pywavelets=1.1.1=py38he774522_2
pywin32=227=py38he774522_1
pywin32-ctypes=0.2.0=py38_1000
pywinpty=0.5.7=py38_0
pyyaml=5.4.1=py38h2bbff1b_1
pyzmq=20.0.0=py38hd77b12b_1
qdarkstyle=2.8.1=py_0
qt=5.9.7=vc14h73c81de_0
qtawesome=1.0.2=pyhd3eb1b0_0
qtconsole=5.0.3=pyhd3eb1b0_0
qtpy=1.9.0=py_0
regex=2021.4.4=py38h2bbff1b_0
requests=2.25.1=pyhd3eb1b0_0
requests-oauthlib=1.3.0=pypi_0
rope=0.18.0=py_0
rsa=4.7.2=pypi_0
rtree=0.9.7=py38h2eaa2aa_1
ruamel_yaml=0.15.100=py38h2bbff1b_0
scikit-image=0.18.1=py38hf11a4ad_0
scikit-learn=0.24.1=py38hf11a4ad_0
scipy=1.6.2=py38h66253e8_1
seaborn=0.11.1=pyhd3eb1b0_0
send2trash=1.5.0=pyhd3eb1b0_1
setuptools=52.0.0=py38haa95532_0
simplegeneric=0.8.1=py38_2
singledispatch=3.6.1=pyhd3eb1b0_1001
sip=4.19.13=py38ha925a31_0
six=1.15.0=py38haa95532_0
snappy=1.1.8=h33f27b4_0
sniffio=1.2.0=py38haa95532_1
snowballstemmer=2.1.0=pyhd3eb1b0_0
sortedcollections=2.1.0=pyhd3eb1b0_0
sortedcontainers=2.3.0=pyhd3eb1b0_0
soupsieve=2.2.1=pyhd3eb1b0_0
sphinx=4.0.1=pyhd3eb1b0_0
sphinxcontrib=1.0=py38_1
sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
sphinxcontrib-htmlhelp=1.0.3=pyhd3eb1b0_0
sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
sphinxcontrib-serializinghtml=1.1.4=pyhd3eb1b0_0
sphinxcontrib-websupport=1.2.4=py_0
spyder=4.2.5=py38haa95532_0
spyder-kernels=1.10.2=py38haa95532_0
sqlalchemy=1.4.7=py38h2bbff1b_0
sqlite=3.35.4=h2bbff1b_0
statsmodels=0.12.2=py38h2bbff1b_0
sympy=1.8=py38haa95532_0
tbb=2020.3=h74a9793_0
tblib=1.7.0=py_0
terminado=0.9.4=py38haa95532_0
testpath=0.4.4=pyhd3eb1b0_0
textdistance=4.2.1=pyhd3eb1b0_0
threadpoolctl=2.1.0=pyh5ca1d4c_0
three-merge=0.1.1=pyhd3eb1b0_0
tifffile=2021.4.8=pyhd3eb1b0_2
tk=8.6.10=he774522_0
toml=0.10.2=pyhd3eb1b0_0
toolz=0.11.1=pyhd3eb1b0_0
tornado=6.1=py38h2bbff1b_0
tqdm=4.59.0=pyhd3eb1b0_1
traitlets=5.0.5=pyhd3eb1b0_0
typed-ast=1.4.2=py38h2bbff1b_1
typing_extensions=3.7.4.3=pyha847dfd_0
ujson=4.0.2=py38hd77b12b_0
unicodecsv=0.14.1=py38_0
uritemplate=3.0.1=pypi_0
urllib3=1.26.4=pyhd3eb1b0_0
vc=14.2=h21ff451_1
virtualenv=20.7.1=pypi_0
vs2015_runtime=14.27.29016=h5e58377_2
watchdog=1.0.2=py38haa95532_1
wcwidth=0.2.5=py_0
webencodings=0.5.1=py38_1
werkzeug=1.0.1=pyhd3eb1b0_0
wheel=0.36.2=pyhd3eb1b0_0
widgetsnbextension=3.5.1=py38_0
win_inet_pton=1.1.0=py38haa95532_0
win_unicode_console=0.5=py38_0
wincertstore=0.2=py38_0
winpty=0.4.3=4
wrapt=1.12.1=py38he774522_1
xlrd=2.0.1=pyhd3eb1b0_0
xlsxwriter=1.3.8=pyhd3eb1b0_0
xlwings=0.23.0=py38haa95532_0
xlwt=1.3.0=py38_0
xmltodict=0.12.0=py_0
xz=5.2.5=h62dcd97_0
yaml=0.2.5=he774522_0
yapf=0.31.0=pyhd3eb1b0_0
zeromq=4.3.3=ha925a31_3
zfp=0.5.5=hd77b12b_6
zict=2.0.0=pyhd3eb1b0_0
zipp=3.4.1=pyhd3eb1b0_0
zlib=1.2.11=h62dcd97_4
zope=1.0=py38_1
zope.event=4.5.0=py38_0
zope.interface=5.3.0=py38h2bbff1b_0
zstd=1.4.5=h04227a9_0
```

 Dependencies have been updated correctly:

Удалить строки
DELETE FROM `fbs-ga360.traffic_managers_activity.google_ads`  WHERE date >= "2021-07-14" AND date <= "2021-07-15"




```
google-ads==13.0.0
  - google-api-core [required: >=1.21.0,<2.0.0, installed: 1.31.1]
    - google-auth [required: >=1.25.0,<2.0dev, installed: 1.34.0]
      - cachetools [required: >=2.0.0,<5.0, installed: 4.2.2]
      - pyasn1-modules [required: >=0.2.1, installed: 0.2.8]
        - pyasn1 [required: >=0.4.6,<0.5.0, installed: 0.4.8]
      - rsa [required: >=3.1.4,<5, installed: 4.7.2]
        - pyasn1 [required: >=0.1.3, installed: 0.4.8]
      - setuptools [required: >=40.3.0, installed: 52.0.0.post20210125]
      - six [required: >=1.9.0, installed: 1.15.0]
    - googleapis-common-protos [required: >=1.6.0,<2.0dev, installed: 1.53.0]
      - protobuf [required: >=3.12.0, installed: 3.17.3]
        - six [required: >=1.9, installed: 1.15.0]
    - packaging [required: >=14.3, installed: 20.9]
      - pyparsing [required: >=2.0.2, installed: 2.4.7]
    - protobuf [required: >=3.12.0, installed: 3.17.3]
      - six [required: >=1.9, installed: 1.15.0]
    - pytz [required: Any, installed: 2021.1]
    - requests [required: >=2.18.0,<3.0.0dev, installed: 2.25.1]
      - certifi [required: >=2017.4.17, installed: 2020.12.5]
      - chardet [required: >=3.0.2,<5, installed: 4.0.0]
      - idna [required: >=2.5,<3, installed: 2.10]
      - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.4]
    - setuptools [required: >=40.3.0, installed: 52.0.0.post20210125]
    - six [required: >=1.13.0, installed: 1.15.0]
  - google-auth-oauthlib [required: >=0.3.0,<1.0.0, installed: 0.4.5]
    - google-auth [required: >=1.0.0, installed: 1.34.0]
      - cachetools [required: >=2.0.0,<5.0, installed: 4.2.2]
      - pyasn1-modules [required: >=0.2.1, installed: 0.2.8]
        - pyasn1 [required: >=0.4.6,<0.5.0, installed: 0.4.8]
      - rsa [required: >=3.1.4,<5, installed: 4.7.2]
        - pyasn1 [required: >=0.1.3, installed: 0.4.8]
      - setuptools [required: >=40.3.0, installed: 52.0.0.post20210125]
      - six [required: >=1.9.0, installed: 1.15.0]
    - requests-oauthlib [required: >=0.7.0, installed: 1.3.0]
      - oauthlib [required: >=3.0.0, installed: 3.1.1]
      - requests [required: >=2.0.0, installed: 2.25.1]
        - certifi [required: >=2017.4.17, installed: 2020.12.5]
        - chardet [required: >=3.0.2,<5, installed: 4.0.0]
        - idna [required: >=2.5,<3, installed: 2.10]
        - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.4]
  - googleapis-common-protos [required: >=1.5.8,<2.0.0, installed: 1.53.0]
    - protobuf [required: >=3.12.0, installed: 3.17.3]
      - six [required: >=1.9, installed: 1.15.0]
  - grpcio [required: >=1.33.2,<2.0.0, installed: 1.39.0]
    - six [required: >=1.5.2, installed: 1.15.0]
  - nox [required: ==2020.12.31, installed: 2020.12.31]
    - argcomplete [required: >=1.9.4,<2.0, installed: 1.12.3]
    - colorlog [required: >=2.6.1,<5.0.0, installed: 4.8.0]
      - colorama [required: Any, installed: 0.4.4]
    - py [required: >=1.4.0,<2.0.0, installed: 1.10.0]
    - virtualenv [required: >=14.0.0, installed: 20.7.1]
      - backports.entry-points-selectable [required: >=1.0.4, installed: 1.1.0]
      - distlib [required: >=0.3.1,<1, installed: 0.3.2]
      - filelock [required: >=3.0.0,<4, installed: 3.0.12]
      - platformdirs [required: >=2,<3, installed: 2.2.0]
      - six [required: >=1.9.0,<2, installed: 1.15.0]
  - proto-plus [required: >=1.18.0,<2.0.0, installed: 1.19.0]
    - protobuf [required: >=3.12.0, installed: 3.17.3]
      - six [required: >=1.9, installed: 1.15.0]
  - PyYAML [required: >=5.1,<6.0, installed: 5.4.1]
  - setuptools [required: >=40.3.0, installed: 52.0.0.post20210125]
```

**Comment by maximbogan** [comment] 2021-08-18 07:04
@wihl Help please..

**Comment by maximbogan** [comment] 2021-08-23 08:13
@wihl Please help..

**Comment by laurachevalier4** [comment] 2021-09-17 19:43
Hey @maximbogan! Apologies for the delay. Are you still experiencing this issue? 

It looks like you're describing a couple things here so I want to make sure I understand:
1. You were seeing an internal error when on version 11.0.2 of the google-ads-python client library, which was prompted by trying to access specific customer IDs retrieved from the customer_client resource (is this correct? Can you point to the specific line that triggered the error, or share an example request ID so we can look into it further?). My understanding is that to avoid this error, you upgraded to version 12.0.0, at which point you started to see the original error you described...
2. `Invalid constructor input`. Is this happening for every customer ID, or only particular IDs? Can you confirm what type customer ID is when you pass it into the `SearchGoogleAdsRequest`? Did upgrading to 12.0.0 resolve the issue you saw in 11.0.2?

There's a lot there, so please correct me if I'm not understanding the issue.

**Comment by klkyouxun** [comment] 2021-09-20 00:05
Hi I am experiencing the same issue. Here are my installed packages:

google-ads==14.0.0
google-api-core==2.0.1
google-auth==2.1.0
google-auth-oauthlib==0.4.6
googleapis-common-protos==1.53.0
proto-plus==1.18.1
protobuf==3.18.0

My Python version:
Python 3.8.8 (default, Apr 13 2021, 12:59:45) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin

My OS:
MacOS Big Sur (11.2.2)

and here's my code:

from google.ads.googleads.client import GoogleAdsClient

credential_dict = {...} # replace this with real credential
client = GoogleAdsClient.load_from_dict(credential_dict)
client.account_id = 'xxxxx' # replace this with real google ads customer ID

google_ads_service = client.get_service("GoogleAdsService", version='v8')

query = '''
        SELECT
           customer_client.resource_name,
           customer_client.client_customer,
           customer_client.level,
           customer_client.manager,
           customer_client.descriptive_name,
           customer_client.id,
           customer_client.test_account,
           customer_client.currency_code           
        FROM
           customer_client
    '''

response = google_ads_service.search(query)
for row in response:
    print(row.customer_client)

Error I got:

request = google_ads_service.SearchGoogleAdsRequest(request)
  File ".../python3.8/site-packages/proto/message.py", line 494, in __init__
    raise TypeError(
TypeError: Invalid constructor input for SearchGoogleAdsRequest: '\n        SELECT\n           customer_client.resource_name,\n           customer_client.client_customer,\n           customer_client.level,\n           customer_client.manager,\n           customer_client.descriptive_name,\n           customer_client.id,\n           customer_client.test_account,\n           customer_client.currency_code           \n        FROM\n           customer_client\n'

Please kindly help. Previously the code ran smoothly until I upgraded my Google ads python SDK to 14.0.0

**Comment by laurachevalier4** [comment] 2021-09-20 15:09
Hey @klkyouxun. I was able to reproduce the error based on your code, and I think the reason for the error is that you are not passing a customer_id to the search request. `search` and `search_stream` require that you pass either: a `SearchGoogleAdsRequest` request object with `customer_id` and `query` fields set, or that you pass named `customer_id` and `query` arguments to the search method; it isn't enough to have the account id set on the client object.

So you would need to change `response = google_ads_service.search(query)` to something like:
```
response = google_ads_service.search(customer_id=customer_id, query=query)
```

Can you give it a try and let me know if it works? Also, can you verify what version of Python you were running before upgrading, and whether the code changed at all?

**Comment by rrzadzki** [comment] 2021-09-22 00:20
I'm doing the following:
```
request = client.get_type("SearchGoogleAdsRequest")
request.customer_id = google_id
request.query = query
request.page_size = page_size
response = ga_service.search(request)
```

where `google_id` is a value that works for other calls. The result for queries on `extension_feed_item` and `asset` both are `Invalid constructor input for SearchGoogleAdsRequest`

**Comment by laurachevalier4** [comment] 2021-09-22 20:18
@rrzadzki can you elaborate on what's different between the erring code and the compiling code? Is it only the query that is different? Can you paste the precise differences here? Also, how are you initializing your `client`? The more info you can provide, the better.

**Comment by rrzadzki** [comment] 2021-09-23 00:55
@laurachevalier4 Thanks for getting back -- as I put together to SSCE I realized my mistake. Incomplete migration, my fault!

**Comment by laurachevalier4** [comment] 2021-09-27 15:16
Closing this, reopen if needed.

**Closed by laurachevalier4** 2021-09-27 15:16 UTC
Labels: bug, triage

**Comment by klkyouxun** [comment] 2021-09-28 08:17
hi @laurachevalier4. thanks for the help. problem solved!
