### ISSUE TITLE
Deprecation warning because of google ads package

### ISSUE THREAD

**Issue by stephan9mertel** [googleads/google-ads-python#181] opened 2019-10-15 14:24 UTC
When executing our system's unit tests we get a bunch full of deprecation warnings like this:
`/google/ads/google_ads/v2/services/enums.py:9744: DeprecationWarning: invalid escape sequence \_`

**Comment by wihl** [comment] 2019-12-27 02:50
Closing this issue as "cannot reproduce." Feel free to reopen it if you can reproduce it with the latest version of the client library. If so, please specify additional details like platform you are using (e.g. Linux / version, OS X, Windows) and the output from `pip freeze`.

**Closed by wihl** 2019-12-27 02:50 UTC

**Comment by stephan9mertel** [comment] 2020-01-02 09:19
@wihl you're right, with the newest version I can't reproduce the issue anymore. Thanks!
