### ISSUE TITLE
Google ads API refresh token issue

### ISSUE THREAD

**Issue by KicksTerz** [googleads/google-ads-python#760] opened 2023-03-30 14:55 UTC
Hi,
It seems that I encounter an issue related to refresh token expiration.
My app wes set to Public and Testing. I've changed it to Internal (as it is what it is intended for), but I still get this error message.
By the way, when I was generating the refresh token I had done it with a gmail account, which is not a user of the workspace that the app is currently restricted to, after switching to Internal.
So, maybe I should generate a new refresh token?

`Traceback (most recent call last):
  File "get_campaigns.py", line 52, in <module>
    googleads_client = GoogleAdsClient.load_from_storage("C:/Users/User/Documents/Python/GoogleAdsApi/google-ads.yaml")
  File "C:\Users\User\AppData\Local\Programs\PythonCodingPack\lib\site-packages\google\ads\googleads\client.py", line 290, in load_from_storage
    kwargs = cls._get_client_kwargs(config_data)
  File "C:\Users\User\AppData\Local\Programs\PythonCodingPack\lib\site-packages\google\ads\googleads\client.py", line 182, in _get_client_kwargs
    "credentials": oauth2.get_credentials(config_data),
  File "C:\Users\User\AppData\Local\Programs\PythonCodingPack\lib\site-packages\google\ads\googleads\oauth2.py", line 114, in get_credentials
    return get_installed_app_credentials(
  File "C:\Users\User\AppData\Local\Programs\PythonCodingPack\lib\site-packages\google\ads\googleads\oauth2.py", line 48, in initialize_credentials_wrapper
    credentials.refresh(Request())
  File "C:\Users\User\AppData\Local\Programs\PythonCodingPack\lib\site-packages\google\oauth2\credentials.py", line 335, in refresh    
    ) = reauth.refresh_grant(
  File "C:\Users\User\AppData\Local\Programs\PythonCodingPack\lib\site-packages\google\oauth2\reauth.py", line 349, in refresh_grant   
    _client._handle_error_response(response_data, retryable_error)
  File "C:\Users\User\AppData\Local\Programs\PythonCodingPack\lib\site-packages\google\oauth2\_client.py", line 73, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'}) `

Any help would be much appreciated,
Many thanks,
Kiril

**Comment by KicksTerz** [comment] 2023-03-31 07:37
When I use the command below in order to obtain the snippet with the authorization URL, nothing happens, the snippet does not appear in the terminal.
`./authenticate_in_web_application.py --client_secrets_path=/secrets.json`

**Comment by KicksTerz** [comment] 2023-03-31 14:06
Hm, I don't see the authenticate_in_web_application.py file in the repo anymore... Has something changed in the authentication process?

**Comment by BenRKarl** [comment] 2023-03-31 15:58
@KicksTerz yes, there's only one process regardless of whether you're using desktop or web flow, see [here](https://developers.google.com/google-ads/api/docs/client-libs/python/oauth-web)

**Comment by KicksTerz** [comment] 2023-04-05 13:49
The error of No such file or directory persists, even after typing the absolute path. The json file name is 100% correct.
I use the following to get it:
`import os

abspath = os.path.abspath("client-secret.json")
print(abspath)`
C:/Users/User/Documents/Python/GoogleAdsApi/client-secret.json

And the error after running the command is below.

`PS C:\Users\User\Documents\Python\GoogleAdsApi>  python generate_user_credentials.py -c /Users/User/Documents/Python/GoogleAdsApi/client-secret.json
Traceback (most recent call last):
  File "generate_user_credentials.py", line 209, in <module>
    main(args.client_secrets_path, configured_scopes)
  File "generate_user_credentials.py", line 61, in main
    flow = Flow.from_client_secrets_file(client_secrets_path, scopes=scopes)
  File "C:\Users\User\AppData\Local\Programs\PythonCodingPack\lib\site-packages\google_auth_oauthlib\flow.py", line 204, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/User/Documents/Python/GoogleAdsApi/client-secret.json'`

Thanks again,
Kiril

**Comment by KicksTerz** [comment] 2023-04-06 08:02
Or maybe I should create a new google cloud project?

**Comment by BenRKarl** [comment] 2023-04-11 18:46
@KicksTerz if the issue is that the filepath is invalid, then I don't think creating a new GCP would help. It _looks_ like you're on Windows, is that right? I wonder if the [OAuth lib](https://google-auth-oauthlib.readthedocs.io/en/latest/_modules/google_auth_oauthlib/flow.html#Flow.from_client_secrets_file) is having trouble parsing the filepath. What exactly do you pass in when you invoke the script? Is it like this:

`python generate_user_credentials.py -c C:/Users/User/Documents/Python/GoogleAdsApi/client-secret.json`

**Comment by KicksTerz** [comment] 2023-04-12 08:06
Yes, I am on windows (vs code) and am using exactly:
`python generate_user_credentials.py -c C:/Users/User/Documents/Python/GoogleAdsApi/client-secret.json`

**Comment by BenRKarl** [comment] 2023-04-28 19:33
@KicksTerz it shouldn't matter if the email addresses are different. Can you clarify whether you're still having problems here, or have you been able to get things sorted out?

**Comment by BenRKarl** [comment] 2023-05-04 13:36
@KicksTerz I'm going to close this out assuming you got everything working. If not please add more details per my question above.

**Closed by BenRKarl** 2023-05-04 13:36 UTC
Labels: question

**Comment by rchadha96** [comment] 2023-06-27 13:53
@BenRKarl I am facing the exact same issue, could you help?
