### ISSUE TITLE
19.0.0 incompatibility -Invalid constructor input for SearchGoogleAdsRequest

### ISSUE THREAD

**Issue by tyleragnew** [googleads/google-ads-python#742] opened 2023-01-26 17:52 UTC
**Describe the bug:**

When upgrading to 

**Steps to Reproduce:**

Make a request to the Google Ads API via the Python SDK on version 19

`    def get(self, query):
        """Fetch query results."""
        service = self.get_service("GoogleAdsService")

        request = self._client.get_type("SearchGoogleAdsRequest")
        request.customer_id = str(self._account_api_id)
        request.query = query
        return service.search(request=request)`

**Expected behavior:**

Get back a SearchGoogleAdsResponse, however we are seeing the following Error Message:
`
Invalid constructor input for SearchGoogleAdsRequest`

This doesn't seem right as the required fields are still only customer_id and query - both of which are strings (https://developers.google.com/google-ads/api/reference/rpc/v12/SearchGoogleAdsRequest)

This request works with Client library 16.0.0.

**Client library version and API version:**
Client library version: 19.0.0
Google Ads API version:

**Request/Response Logs:**

`[2023-01-26 17:30:07 +0000] ERROR   Task                           {"job": "b'google_58'", "event": "Exception(' GoogleSync failed for : Client 94, Account 58, Account Api Id (2958490366, 94), Error Message Invalid constructor input for SearchGoogleAdsRequest: customer_id: \"2958490366\"\\nquery: \"\\\\n            SELECT\\\\n                customer.manager,\\\\n                customer.currency_code,\\\\n                customer.id,\\\\n                customer.time_zone,\\\\n                customer.descriptive_name,\\\\n                customer.test_account\\\\n            FROM customer\\\\n            LIMIT 1\\\\n        \"\\n')", "logger": "b'everquote.syncer.core.utilities.Task'", "level": "b'error'", "timestamp": "b'2023-01-26T12:30:07.762368-05:00'"}`

**Anything else we should know about your project / environment:**

**Comment by BenRKarl** [comment] 2023-02-23 15:13
@tyleragnew I'm not able to reproduce this locally with the latest version of the library, or in version 19.0.0. Here's a copy-paste from a local repl:

```sh
>>> from google.ads.googleads.client import GoogleAdsClient
>>> client = GoogleAdsClient.load_from_storage()
>>> svc = client.get_service("GoogleAdsService")
>>> request = client.get_type("SearchGoogleAdsRequest")
>>> request.customer_id = "123456789"
>>> request.query = "select campaign.name from campaign"

[ Returns INVALID_CUSTOMER_ID error, as I would expect ]
```

I notice the error logs you pasted don't appear to be from the API or the client library, is it possible this error is stemming from a different location in your application?

**Comment by BenRKarl** [comment] 2023-03-14 18:20
@tyleragnew closing this out for now, but if you continue seeing these issues please comment here with more details.

**Closed by BenRKarl** 2023-03-14 18:20 UTC
Labels: bug, triage
