### ISSUE TITLE
GoAway503 Error

### ISSUE THREAD

**Issue by skiwan** [googleads/google-ads-python#277] opened 2020-05-22 13:43 UTC
Hey

we are using basically the full API at out company (PIerce AB, Sweden) to fully automate our google shoppping campaign setup. This is about 30+ accounts. So far everything has mainly been working very well and using the api is really good. 

The only problem we are running in from time to time is a 503 GOAWAY that we receive from the API and I dont know why.

We have a developer token and we are not reaching any quota limits with our code. I also make sure to limit the amount of operations we are sending to the api. Still sometimes (very irregular timings) we receive a 503 during execution of our script. The major problem that this creates for us is:

Our script usually runs many minutes (somewhere around 2h per account) now if we receive a 503 this for one interupts the script and we manually have to start it again and second it sometimes creates corrupted fragements. For example if we query for adgroups with product listing groups we will get some adgroups from the api that in the google ads UI dont have any product listing groups.

Why do we receive this 503 GOAWAY Error and how can we prevent it?

**Comment by BenRKarl** [comment] 2020-05-26 14:31
@skiwan can you share the error response you get when this occurs?

**Comment by skiwan** [comment] 2020-05-26 14:34
Request made: ClientCustomerId: 4000932199, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v3.services.AdGroupCriterionService/MutateAdGroupCriteria, RequestId: None, IsFault: True, FaultMessage: GOAWAY received
Traceback (most recent call last):
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 216, in __call__
    response, ignored_call = self._with_call(request,
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_channel.py", line 333, in result
    raise self
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 241, in continuation
    response, call = self._thunk(new_method).with_call(
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 266, in with_call
    return self._with_call(request,
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_channel.py", line 333, in result
    raise self
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 241, in continuation
    response, call = self._thunk(new_method).with_call(
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 266, in with_call
    return self._with_call(request,
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 254, in _with_call
    call = self._interceptor.intercept_unary_unary(continuation,
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\ads\google_ads\interceptors\exception_interceptor.py", line 168, in intercept_unary_unary
    self._handle_grpc_failure(response)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\ads\google_ads\interceptors\exception_interceptor.py", line 140, in _handle_grpc_failure
    raise self._get_error_from_response(response)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 241, in continuation
    response, call = self._thunk(new_method).with_call(
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_channel.py", line 837, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "GOAWAY received"
        debug_error_string = "{"created":"@1590488112.469000000","description":"Error received from peer ipv4:216.58.207.202:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"GOAWAY received","grpc_status":14}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "merchantCenter.py", line 991, in <module>
    create_new_productlist_normal(client, google_ads_id, ad_id, cat_id, cats_to_pids[cat_id], ad_group_criterion_service, ad_group_service)
  File "merchantCenter.py", line 611, in create_new_productlist_normal
    response = ad_group_criterion_service.mutate_ad_group_criteria(customer_id, operations)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\ads\google_ads\v3\services\ad_group_criterion_service_client.py", line 297, in mutate_ad_group_criteria
    return self._inner_api_calls['mutate_ad_group_criteria'](request, retry=retry, timeout=timeout, metadata=metadata)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\gapic_v1\method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\retry.py", line 184, in retry_target
    return target()
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ServiceUnavailable: 503 GOAWAY received



hope that helps

**Comment by BenRKarl** [comment] 2020-06-01 19:35
@skiwan I'm still looking into this issue. In the meantime, do you think you could add a print statement similar to as I've done in [this PR](https://github.com/googleads/google-ads-python/pull/280/files) to print the raw trailing_metadata from a request that results in this error?

**Comment by skiwan** [comment] 2020-06-09 08:27
Ill try to add t and execute the script on one of our new markets. As soon as I get an error with trailing_metadata I will let you know

**Comment by skiwan** [comment] 2020-06-09 10:27
Im currenlty using the following code to handle google ads exceptions

Could you tell me how to incoperate the trailing metadata here because im not sure how, with this setup I can get the request

def print_error_and_exit_process(error):
	print('Request with ID "{}" failed with status "{}" and includes the '
			'following errors:'.format(error.request_id, error.error.code().name))
	for error in error.failure.errors:
		print('\tError with message "{}".'.format(error.message))
		if error.location:
			for field_path_element in error.location.field_path_elements:
				print('\t\tOn field: {}'.format(
					field_path_element.field_name))
	#sys.exit(1)


all api calls are wrapped in a try catch like

try:
    google-ads-call()
except GoogleAdsException as ex:
		print_error_and_exit_process(ex)

**Comment by skiwan** [comment] 2020-09-18 12:54
Hey @BenRKarl , we are still regularly running into this error which is a huge problem for us.

I activated logging. This is the log for the latest test we made that ran into the 503 error.


[2020-09-18 11:25:55,101 - INFO] Request made: ClientCustomerId: 9465697505, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v3.services.AdGroupAdService/MutateAdGroupAds, RequestId: CuG_Jx7FW-VRuuK_Y28TZg, IsFault: False, FaultMessage: None
[2020-09-18 11:25:55,109 - INFO] Request
-------
Method: /google.ads.googleads.v3.services.AdGroupAdService/MutateAdGroupAds
Host: googleads.googleapis.com:443
Headers: {
  "developer-token": "REDACTED",
  "login-customer-id": "4156396339",
  "x-goog-api-client": "gl-python/3.8.0 grpc/1.27.2 gax/1.16.0 gapic/5.0.1",
  "x-goog-request-params": "customer_id=9465697505"
}
Request: customer_id: "9465697505"
operations {
  create {
    status: PAUSED
    ad_group {
      value: "customers/9465697505/adGroups/117822079388"
    }
    ad {
      expanded_dynamic_search_ad {
        description {
          value: "Motorcross Parts, Gear & Accessories shipping worldwide with the best service and price."
        }
        description2 {
          value: "Jumps are for show, corners are for dough and www.24mx.ie is to cover them both!"
        }
      }
    }
  }
}


Response
-------
Headers: {}
Fault: {
  "created": "@1600421155.109000000",
  "description": "Error received from peer ipv4:216.58.211.138:443",
  "file": "src/core/lib/surface/call.cc",
  "file_line": 1056,
  "grpc_message": "GOAWAY received",
  "grpc_status": 14
}

[2020-09-18 11:25:55,109 - WARNING] Request made: ClientCustomerId: 9465697505, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v3.services.AdGroupAdService/MutateAdGroupAds, RequestId: None, IsFault: True, FaultMessage: GOAWAY received
Traceback (most recent call last):
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 216, in __call__
    response, ignored_call = self._with_call(request,
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_channel.py", line 333, in result
    raise self
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 241, in continuation
    response, call = self._thunk(new_method).with_call(
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 266, in with_call
    return self._with_call(request,
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_channel.py", line 333, in result
    raise self
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 241, in continuation
    response, call = self._thunk(new_method).with_call(
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 266, in with_call
    return self._with_call(request,
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 254, in _with_call
    call = self._interceptor.intercept_unary_unary(continuation,
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\ads\google_ads\interceptors\exception_interceptor.py", line 168, in intercept_unary_unary
    self._handle_grpc_failure(response)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\ads\google_ads\interceptors\exception_interceptor.py", line 140, in _handle_grpc_failure
    raise self._get_error_from_response(response)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_interceptor.py", line 241, in continuation
    response, call = self._thunk(new_method).with_call(
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_channel.py", line 837, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\grpc\_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "GOAWAY received"
        debug_error_string = "{"created":"@1600421155.109000000","description":"Error received from peer ipv4:216.58.211.138:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"GOAWAY received","grpc_status":14}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dsa_campaign_script.py", line 855, in <module>
    create_expanded_dsa(client, google_ads_id, ad_group_res_name, ad_group_ad_service, descr)
  File "dsa_campaign_script.py", line 384, in create_expanded_dsa
    ad_group_ad_response = ad_group_ad_service.mutate_ad_group_ads(
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\ads\google_ads\v3\services\ad_group_ad_service_client.py", line 297, in mutate_ad_group_ads
    return self._inner_api_calls['mutate_ad_group_ads'](request, retry=retry, timeout=timeout, metadata=metadata)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\gapic_v1\method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\retry.py", line 184, in retry_target
    return target()
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "E:\MerlinsProgrammingPlayground\env\lib\site-packages\google\api_core\grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ServiceUnavailable: 503 GOAWAY received

**Comment by BenRKarl** [comment] 2021-03-31 18:04
@skiwan just checking if these errors are still an issue for you. I was never able to find a root cause, and am hoping they might have been transient.

**Comment by BenRKarl** [comment] 2021-04-12 17:17
Closing this assuming the errors have stopped, but please reopen if that's not the case.

**Closed by BenRKarl** 2021-04-12 17:17 UTC

**Comment by shivamsngh** [comment] 2025-01-20 10:27
This is still an issue
