### ISSUE TITLE
LISTING_GROUP_SUBDIVISION_REQUIRES_OTHERS_CASE

### ISSUE THREAD

**Issue by saikumarsura-ts** [googleads/google-ads-python#321] opened 2020-10-06 08:24 UTC
Hi Guys,
I am facing a similar issue 

Subdivisions from all hotels in adGroup
>Trying to create a root node with temporary "-1" negative id as subdivisions.
> Assigning root resource name to child Unit node as the parent resource name.
Also, Suggest a solution on how to subdivide multiple hotels using APIs or postman.
URL:
https://googleads.googleapis.com/v5/customers/1138518998/adGroupCriteria:mutate
Body:
```
{
    "operations": [
        {
            "create": {
                "resource_name": "customers/1138518998/adGroupCriteria/108695051612~-1",
                "status": "ENABLED",
                "listing_group": {
                    "type": "SUBDIVISION"
                }
            }
        },
        {
            "create": {
                "resource_name": "customers/1138518998/adGroupCriteria/108695051612~-2",
                "percent_cpc_bid_micros": 100000,
                "status": "ENABLED",
                "listing_group": {
                    "type": "UNIT",
                    "case_value": {
                        "hotel_class": {
                            "value": 5
                        }
                    },
                    "parent_ad_group_criterion": "customers/1138518998/adGroupCriteria/108695051612~-1"
                }
            }
        },
        {
            "create": {
                "resource_name": "customers/1138518998/adGroupCriteria/108695051612~-3",
                "status": "ENABLED",
                "listing_group": {
                    "type": "SUBDIVISION",
                    "case_value": {
                        "hotel_class": {}
                    },
                    "parent_ad_group_criterion": "customers/1138518998/adGroupCriteria/108695051612~-1"
                }
            }
        },
        {
            "create": {
                "resource_name": "customers/1138518998/adGroupCriteria/108695051612~-4",
                "percent_cpc_bid_micros": 100000,
                "status": "ENABLED",
                "listing_group": {
                    "type": "UNIT",
                    "case_value": {
                        "hotelCountryRegion": {
                            "country_region_criterion": "geoTargetConstants/2710"
                        }
                    },
                    "parent_ad_group_criterion": "customers/1138518998/adGroupCriteria/108695051612~-3"
                }
            }
        },
        {
            "create": {
                "resource_name": "customers/1138518998/adGroupCriteria/108695051612~-5",
                "status": "ENABLED",
                "listing_group": {
                    "type": "SUBDIVISION",
                    "case_value": {
                        "hotel_country_region": {}
                    },
                    "parent_ad_group_criterion": "customers/1138518998/adGroupCriteria/108695051612~-3"
                }
            }
        }
    ]
}
Response:
{
    "error": {
        "code": 400,
        "message": "Request contains an invalid argument.",
        "status": "INVALID_ARGUMENT",
        "details": [
            {
                "@type": "type.googleapis.com/google.ads.googleads.v5.errors.GoogleAdsFailure",
                "errors": [
                    {
                        "errorCode": {
                            "criterionError": "LISTING_GROUP_SUBDIVISION_REQUIRES_OTHERS_CASE"
                        },
                        "message": "Subdivided listing groups must have an \"others\" case.",
                        "trigger": {
                            "stringValue": "ProductPartition{id=TempCriterionId{id=5}, bidSimulatorStatus=null, partitionType=SUBDIVISION, parentCriterionId=TempCriterionId{id=3}, productGroup=null, productGroupObsoleteStatus=null, caseValue=HotelCountry{type=HOTEL_COUNTRY, value=null}, decisionPath=[HotelClass{type=HOTEL_CLASS, value=null}, HotelCountry{type=HOTEL_COUNTRY, value=null}], salesCountry=null, merchantId=null, hasPromotedSuggestion=null}"
                        }
                    }
                ]
            }
        ]
    }
}


```

Thanks in advance.

**Comment by BenRKarl** [comment] 2021-04-13 18:47
Closing as duplicate of #320

**Closed by BenRKarl** 2021-04-13 18:47 UTC
