### ISSUE TITLE
Proxy issue appearing in 10.0.0

### ISSUE THREAD

**Issue by thatch** [googleads/google-ads-python#423] opened 2021-05-10 13:31 UTC
**Describe the bug:**

We use an http proxy to communicate using the google-ads library.  This worked fine on previous versions by setting the `http_proxy` and `https_proxy` env vars.  When updating to 10.0.0 or later, I get the following error when using search:

```
         debug_error_string = "{"created":"@1620489718.036336118","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5419,"referenced_errors":[{"
created":"@1620489718.036326964","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
```

This problem exists on 10.0.0 unmodified, 10.0.0 with PR 405 applied (with proxy set in yaml), and also on 11.0.0 unmodified.  I am 100% sure that the grpc version is the same between working on google-ads 9.0.0 and failing on 10.0.0.

I've run a bisect which points at either 6c242d341fe9b4764a4377807d698ccc8a7aef74, or the changes we had to make in our script to deal with the disruptive api changes.  Do you have a more granular version of that commit that we could continue bisecting on?

**Steps to Reproduce:**
Internal build, sorry.  I'm happy to test things to provide simplified versions or add debugging information as you'd like.

**Expected behavior:**
Proxy support continues to work.

**Screenshots:**
n/a

**Library version and API version:**

I see the failed call using `/google.ads.googleads.v5.services.GoogleAdsService/Search`

```
google-api-core 1.22.1
grpcio 1.37.1
google-ads 10.0.0 (or 11.0.0 if you'd rather)
```

**Request/Response Logs:**
I can generate these if you let me know what you're looking for.

**Additional context:**
n/a

**Comment by laurachevalier4** [comment] 2021-05-10 14:48
Hey @thatch! Thanks for providing all this info. A couple things:
1. Are you using distinct endpoints for http and https? As I understand it from the [grpc docs](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md#grpc-environment-variables), only one of http_proxy and https_proxy will actually be used. Can you retry with setting only http_proxy and not https_proxy, and post the error message that results from the same Search call?
2. Are you getting this exact error message in all of the cases you outlined (v10 w/o #405, v10 with #405 applied, and v11)? In the cases of v10 with PR #405 applied and v11, are you getting the same errors with and without setting the http_proxy value in your google-ads.yaml? Otherwise, can you post the different errors you're getting per each case (or let us know if they are the same in every case):
    * v10
      * http_proxy is set as an env var
    * v10 with 405:
      * http_proxy is set as an env var and in the yaml
      * http_proxy is set only as an env var
      * http_proxy is set only in the yaml
    * v11
      * http_proxy is set as an env var and in the yaml
      * http_proxy is set only as an env var
      * http_proxy is set only in the yaml

**Comment by thatch** [comment] 2021-05-10 21:46
Adding @dfaradjev who has more experience with testing this.

**Comment by dfaradjev** [comment] 2021-05-10 22:04
Hi @laurachevalier4 , 
I will try to jump in to answer some of your questions:
1. Setting http_proxy in yaml or in the environment does not change anthing on our side. We get 
`google.auth.exceptions.TransportError: HTTPSConnectionPool(host='accounts.google.com', port=443): Max retries exceeded with url: /o/oauth2/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb15273c400>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
`
Only if we set https_proxy in the environment things are looking different...
`Response
-------
Headers: {}
Fault: {
  "created": "@1620675396.953970565",
  "description": "Failed to pick subchannel",
  "file": "src/core/ext/filters/client_channel/client_channel.cc",
  "file_line": 5419,
  "referenced_errors": [
    {
      "created": "@1620675396.953960685",
      "description": "failed to connect to all addresses",
      "file": "src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc",
      "file_line": 397,
      "grpc_status": 14
    }
  ]
}
`
2. We get exactly the same error message with or without setting http_proxy in the yaml file. (after https_proxy env. variable is set)

Really appreciate your help!

**Comment by thatch** [comment] 2021-05-10 22:10
@dfaradjev two more questions -- on 9.0.0 where it's successful, is it fetching the v5 endpoint?  And does it fail identically on 10.0.0 and 11.0.0?

**Comment by dfaradjev** [comment] 2021-05-10 22:47
v9.0.0 is working fine when I set https_proxy environment variable. It is fetching the v5 endpoint.
v10.0.0 is not working for the same reason as v11.0.0 -` google.api_core.exceptions.ServiceUnavailable: 503 failed to connect to all addresses`

**Comment by laurachevalier4** [comment] 2021-05-11 23:31
@dfaradjev I see you confirmed the outcome with the https_proxy env var set and http_proxy not set in the yaml, but can you also make sure the http_proxy env variable is empty and let me know the behavior (in v11)? Also, do you have a longer stack trace you can provide? 

Thanks!

**Comment by dfaradjev** [comment] 2021-05-11 23:51
Confirming, I got the same error when http_proxy env. variable was not set at all.
Here is the full traceback(redacted):



```
[2021-05-11 16:42:18,190 - INFO] Request
-------
Method: /google.ads.googleads.v5.services.GoogleAdsService/Search
Host: googleads.googleapis.com
Headers: {
  "developer-token": "REDACTED",
  "login-customer-id": "<MY_CUSTOMER_ID>",
  "x-goog-api-client": "gl-python/3.8.6 grpc/1.37.1 gax/1.22.1",
  "x-goog-request-params": "customer_id=<MY_CUSTOMER_ID>"
}
Request: customer_id: "<MY_CUSTOMER_ID>"
query: "SELECT customer_client.id FROM customer_client WHERE customer_client.manager = True"
page_size: 3000


Response
-------
Headers: {}
Fault: {
  "created": "@1620776538.189482558",
  "description": "Failed to pick subchannel",
  "file": "src/core/ext/filters/client_channel/client_channel.cc",
  "file_line": 5419,
  "referenced_errors": [
    {
      "created": "@1620776538.189472689",
      "description": "failed to connect to all addresses",
      "file": "src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc",
      "file_line": 397,
      "grpc_status": 14
    }
  ]
}

[2021-05-11 16:42:18,190 - WARNING] Request made: ClientCustomerId: <MY_CUSTOMER_ID>, Host: googleads.googleapis.com, Method: /google.ads.googleads.v5.services.GoogleAdsService/Search, RequestId: None, IsFault: True, FaultMessage: failed to connect to all addresses
Traceback (most recent call last):
  File "/data/users/my_user/my_path/ads_report_downloader#link-tree/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/data/users/my_user/my_path/ads_report_downloader#link-tree/grpc/_interceptor.py", line 216, in __call__
    response, ignored_call = self._with_call(request,
  File "/data/users/my_user/my_path/ads_report_downloader#link-tree/grpc/_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "/data/users/my_user/my_path/ads_report_downloader#link-tree/grpc/_channel.py", line 343, in result
    raise self
  File "/data/users/my_user/my_path/ads_report_downloader#link-tree/grpc/_interceptor.py", line 241, in continuation
    response, call = self._thunk(new_method).with_call(
  File "/data/users/my_user/my_path/ads_report_downloader#link-tree/grpc/_interceptor.py", line 266, in with_call
    return self._with_call(request,
  File "/data/users/my_user/my_path/ads_report_downloader#link-tree/grpc/_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "/data/users/my_user/my_path/ads_report_downloader#link-tree/grpc/_channel.py", line 343, in result
    raise self
  File "/data/users/my_user/my_path/ads_report_downloader#link-tree/grpc/_interceptor.py", line 241, in continuation
    response, call = self._thunk(new_method).with_call(
  File "/data/users/my_user/my_path/ads_report_downloader#link-tree/grpc/_interceptor.py", line 266, in with_call
    return self._with_call(request,
  File "/data/users/my_user/my_path/ads_report_downloader#link-tree/grpc/_interceptor.py", line 254, in _with_call
    call = self._interceptor.intercept_unary_unary(continuation,
  File "/data/users/my_user/my_path/ads_report_downloader#link-tree/google/ads/googleads/interceptors/exception_interceptor.py", line 169, in intercept_unary_unary
    self._handle_grpc_failure(response)
  File "/data/users/my_user/my_path/ads_report_downloader#link-tree/google/ads/googleads/interceptors/exception_interceptor.py", line 141, in _handle_grpc_failure
    raise self._get_error_from_response(response)
  File "/data/users/my_user/my_path/ads_report_downloader#link-tree/grpc/_interceptor.py", line 241, in continuation
    response, call = self._thunk(new_method).with_call(
  File "/data/users/my_user/my_path/ads_report_downloader#link-tree/grpc/_channel.py", line 957, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "/data/users/my_user/my_path/ads_report_downloader#link-tree/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1620776538.189482558","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5419,"referenced_errors":[{"created":"@1620776538.189472689","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 38, in <module>
  File "<string>", line 36, in __run
  File "/local_path/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/local_path/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/users/my_user/my_path/ads_report_downloader#link-tree/my_code_path/ads_report_downloader.py", line 297, in <module>
    manager_accounts = get_accounts_by_type(mcc_client_id, True)
  File "/data/users/my_user/my_path/ads_report_downloader#link-tree/my_code_path/ads_report_downloader.py", line 44, in get_accounts_by_type
    results = ga_service.search(request=search_request)
  File "/data/users/my_user/my_path/ads_report_downloader#link-tree/google/ads/googleads/v5/services/services/google_ads_service/client.py", line 2140, in search
    response = rpc(
  File "/data/users/my_user/my_path/ads_report_downloader#link-tree/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/data/users/my_user/my_path/ads_report_downloader#link-tree/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ServiceUnavailable: 503 failed to connect to all addresses

```

**Comment by thatch** [comment] 2021-05-12 15:47
It would appear that the CONNECT is different, and dropped the port number in 10.0.0

```
# in 9.0.0
CONNECT googleads.googleapis.com:443 HTTP/1.0
# in 10.0.0
CONNECT googleads.googleapis.com HTTP/1.0
```

**Comment by thatch** [comment] 2021-05-12 16:36
My proxy admin is advising that grpc is sending non-compliant CONNECT requests.  The port is required as part of the "authority form", per

https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.6
https://datatracker.ietf.org/doc/html/rfc7230#section-5.3.3

do you know if grpc has a policy of assuming 443 and should be adding or at least validating it before issuing the request?  The source in `src/core/ext/filters/client_channel/http_connect_handshaker.cc` refers to it as "server_name" without any reference to it including a port.

**Comment by laurachevalier4** [comment] 2021-05-12 18:19
That additional info is really useful, thanks. I think I know what's happening here, can you try something to confirm: In your google-ads.yaml, add an `endpoint` config that's set to `googleads.googleapis.com:443`?

**Comment by dfaradjev** [comment] 2021-05-12 19:28
@laurachevalier4 Adding endpoint: `googleads.googleapis.com:443` to the yaml seems to help. Will keep testing. Is this a permanent solution or a temporary workaround?
Thanks

**Comment by laurachevalier4** [comment] 2021-05-12 19:40
@dfaradjev this is a temporary workaround. Thanks for testing! Please let us know the outcome as you keep testing. Since it seems to work (unless you say otherwise), we're looking at the possible permanent solutions this points us to.

**Comment by laurachevalier4** [comment] 2021-05-13 17:48
@dfaradjev and @thatch to help us determine what's going to be the best permanent solution for this, can you provide a couple more details? 
1. With the `endpoint` field removed from the config (i.e. with the same setup you had when seeing the error), set the following grpc tracing environment variables and rerun the Search query:
    * `GRPC_TRACE=client_channel_routing,cares_resolver,connectivity_state`
    * `GRPC_VERBOSITY=debug`
**What are the output logs when the Search query is rerun?**
2. Confirm whether the proxy is missing [ALPN](https://en.wikipedia.org/wiki/Application-Layer_Protocol_Negotiation).

**Comment by ejona86** [comment] 2021-05-13 18:41
FWIW, I think it is clear (via https://github.com/googleads/google-ads-python/issues/423#issuecomment-839881082) that gRPC is doing the wrong thing here, so fixing it in gRPC (https://github.com/grpc/grpc/issues/26227) seems the appropriate permanent solution. That said, I don't work on C core so we'll need to see what they think.

I don't think ALPN has any impact here, as the proxy is not doing TLS at all (it's a TCP tunnel).

**Comment by jalopezsilva** [comment] 2021-05-13 18:47
> Confirm whether the proxy is missing ALPN.

Our proxy has a TCP endpoint and a TLS endpoint. Through the TLS endpoint we support negotiating h1 / h2 through ALPN. That said as @ejona86 mentioned, it's unclear why the ALPN would affect anything here? The H1 CONNECT sent is clearly malformed.

**Comment by laurachevalier4** [comment] 2021-05-13 19:19
Looks like this is attributed to the [grpc bug](grpc/grpc#26227), so I'm going to close this and recommend the [temporary workaround](https://github.com/googleads/google-ads-python/issues/423#issuecomment-839994655) in the meantime, until that grpc bug is fixed.

**Closed by laurachevalier4** 2021-05-13 19:19 UTC
Labels: bug, triage

**Comment by RangerWolf** [comment] 2021-11-08 10:50
@BenRKarl @laurachevalier4  Hello, I upgrade to latest version, still not be able to use proxy.
```
python 3.9
grpcio 1.41.1
google-ads 14.0.1
```

I try with [tmp workaroud](https://github.com/googleads/google-ads-python/issues/423#issuecomment-839994655) but it does not work either.

Here is a sample code to display where I got stuck:
```python
credentials = {
    "developer_token": 'xxxx',
    "refresh_token": 'xxxx',
    "client_id": 'xxxx',
    "client_secret": 'xxxx',
    "login_customer_id": 'xxxx',
    "http_proxy": "http://host-ip:port",
    "version": "v9",
    "use_proto_plus": True,
}
client = GoogleAdsClient.load_from_dict(credentials)
```

After debug, I found it stuck by urllib3 and urllib3 decide not to use proxy for https://accounts.google.com

![image](https://user-images.githubusercontent.com/3512774/140728864-33196692-f66d-46af-8f5b-44144dbb3f23.png)


From above image, you can see that:
```python
proxy_keys = ['https://accounts.google.com', 'https', 'all://accounts.google.com', 'all']

proxies is OrderedDict([('http', 'http://xxxxx:yyyy')])
```
So function `select_proxy` will return `None` 

Maybe the solution is to support `https_proxy` in config?
