### ISSUE TITLE
update campaign standard bidding strategy

### ISSUE THREAD

**Issue by tommaso-castellani** [googleads/google-ads-python#564] opened 2022-01-13 15:25 UTC
How can I update a campaign switching between standard bidding strategy MAXIMIZE_CONVERSIONS to MANUAL_CPC and the other way around?

I get no errors from the api, but the optimization is not performed:

Input:
```
d = {
    "resourceName": "customers/123456789/campaigns/123456789",
    "biddingStrategyType": "MANUAL_CPC",
    'manualCpc': {'enhancedCpcEnabled': False}
}

updater = GoogleUpdater(account=a)
entity_service = updater.googleads_client.get_service('CampaignService', version=updater.VERSION)
operation = updater.googleads_client.get_type('CampaignOperation', version=updater.VERSION)
entity_proto = ParseDict(d, operation.update._pb)
fm = protobuf_helpers.field_mask(None, entity_proto)
operation.update_mask.CopyFrom(fm)
entity_service.mutate_campaigns(customer_id=updater.account.remote_id, operations=[operation])
```

Output:
```
results {
  resource_name: "customers/123456789/campaigns/123456789"
}
```

**Comment by BenRKarl** [comment] 2022-01-27 18:42
Hi @tommaso-castellani can you share the `update_mask` from your request logs?

My hunch is that you may need to add the bidding strategy field path manually to the update mask.

**Comment by bruno911** [comment] 2022-01-27 20:30
I believe what you are saying is something like this:

```
entity_service = updater.googleads_client.get_service('CampaignService', version=updater.VERSION)
operation = updater.googleads_client.get_type('CampaignOperation', version=updater.VERSION)
entity_proto = ParseDict(d, operation.update._pb)
fm = protobuf_helpers.field_mask(None, entity_proto)
**fm.paths.append('manual_cpc')**
operation.update_mask.CopyFrom(fm)
entity_service.mutate_campaigns(customer_id=updater.account.remote_id, operations=[operation])
```

This would fail with:

```
>, errors {
  error_code {
    field_mask_error: FIELD_HAS_SUBFIELDS
  }
  message: "The field mask updated a field with subfields: \'manual_cpc\'."
  location {
    field_path_elements {
      field_name: "operations"
      index: 0
    }
  }
}

```
I believe this is related to this:

[https://github.com/googleads/google-ads-java/issues/272](https://github.com/googleads/google-ads-java/issues/272)

And also to this:

[https://www.mail-archive.com/adwords-api@googlegroups.com/msg72915.html](https://www.mail-archive.com/adwords-api@googlegroups.com/msg72915.html)

Basically, if we do:

```
campaign.manual_cpc = updater.googleads_client.get_type('ManualCpc')
campaign.manual_cpc.enhanced_cpc_enabled = True
```

It works, but we cannot then set any bidding strategy without parameters, as for example ManualCpc with .enhanced_cpc_enabled = False, or MaximizeConversions.
It seems a bug that that is being dragged from v6 until v9 included.
Any ideas would be really useful, but it may be at the Google Core level see:

[https://githubplus.com/googleapis/python-api-core/issues/231](https://githubplus.com/googleapis/python-api-core/issues/231)
[https://githubplus.com/googleapis/python-api-core/issues/232](https://githubplus.com/googleapis/python-api-core/issues/232)

Note we have also tried this alternative with similar results, the bidding strategy doesn't change:

```
empty_bidding = updater.googleads_client.get_type('ManualCpc')
updater.googleads_client.copy_from(campaign.manual_cpc, empty_bidding)
```

**Comment by BenRKarl** [comment] 2022-02-17 15:37
@bruno911 Is it possible to add `"manual_cpc.enhanced_cpc_enabled"` to the update mask without setting the field? That should indicate to the API that you're explicitly setting this field, with enhanced_cpc_enabled = false.

**Comment by devchas** [comment] 2022-02-25 21:33
@BenRKarl the workaround you suggested should work. However, I think the problematic behavior is caused by https://github.com/googleapis/python-api-core/issues/230 rather than https://github.com/googleads/google-ads-java/issues/272.

The issue in https://github.com/googleads/google-ads-java/issues/272 is specifically related to messages with no fields set - for example, if the `manual_cpc` object were created on the campaign without setting `enhanced_cpc_enabled` at all (which is technically an invalid request because `manual_cpc.enhanced_cpc_enabled` is an optional field).

I added a comment to https://github.com/googleapis/python-api-core/issues/230 to clarify what we're trying to achieve here, but I think a fix to that issue should resolve this one.

**Comment by BenRKarl** [comment] 2022-03-22 19:13
@devchas thanks for clarifying and re-opening that bug in api-core. I'm going to close this for now given the workaround, @bruno911 feel free to follow the [api-core bug](https://github.com/googleapis/python-api-core/issues/230) and once we update our dependency to pick up that change this workflow should be easier.

**Closed by BenRKarl** 2022-03-22 19:13 UTC
Labels: question
