### ISSUE TITLE
ChangeStatus get/search failure using resource_name

### ISSUE THREAD

**Issue by j-walker23** [googleads/google-ads-python#245] opened 2020-03-16 08:08 UTC
Hello, ran into a random issue, so I figured i'd pass it along.

Neither ChangeStatusService nor GoogleAdsService can get a resource using a resource_name from previous search results.

```
  service = client.get_service('ChangeStatusService')
  ga = client.get_service('GoogleAdsService')

  q = f"""
  select change_status.resource_name
  from change_status
  order by change_status.last_change_date_time desc
  limit 1
  """

  resource_name = None
  for row in ga.search(self.cid, query=q):
    resource_name = row.change_status.resource_name

  assert resource_name

  q = f"""
  select
    change_status.resource_status
  , change_status.resource_type
  , change_status.last_change_date_time
  from change_status
  where change_status.resource_name = '{resource_name}'
  """

  try:
    # Try GoogleAds
    list(ga.search(self.cid, query=q))
  except:
    # request_error: BAD_RESOURCE_ID
    pass

  try:
    # Try debugging only service get method
    list(service.get_change_status(resource_name))
  except:
    # request_error: BAD_RESOURCE_ID
    pass
```

![Error info here](https://user-images.githubusercontent.com/2018885/76735551-bcad9000-672a-11ea-9ee1-867c78dc95f5.png)

ps. That image shows a customer number, I can't think of a way that's unsafe, since auth would be required and i didn't show any tokens. But, please let me know if i'm wrong about that.

**Comment by wihl** [comment] 2020-03-16 12:39
The error is actually coming from the `list(service.get_change_status(resource_name))`. ChangeStatus returns a [ChangeStatus](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v3.resources#google.ads.googleads.v3.resources.ChangeStatus) resource which is not iterable. Since you are coercing a non-iterable into a list, you are generating a `TypeError: 'ChangeStatus' object is not iterable` exception.

**Comment by j-walker23** [comment] 2020-03-16 12:45
Sorry, I shouldn’t have put pseudo code.
My code is heavily abstracted, and I forgot how to use it plainly for the
examples.

I included an image so you can see the error.

**Comment by wihl** [comment] 2020-03-16 13:37
Ok, I've been able to reproduce your issue with your specific customer ID and Ad Group ID. I'll file a bug.

**Comment by j-walker23** [comment] 2020-03-16 14:02
Perfect, thanks so much for your help as always!

**Comment by BenRKarl** [comment] 2020-04-10 19:13
@j-walker23 it seems that a fix for this issue may have been released, can you verify whether you're still having this problem?

**Comment by j-walker23** [comment] 2020-04-14 23:50
@BenRKarl Sorry it took me so long to see this!

After updating to the latest, I seem to still be getting the error mentioned above, 
but only with `resource_type: CAMPAIGN`.

Other resource types that I've tried are working successfully.

Here is a couple of new ChangeStatus resource_names from today that are erroring.

`customers/5176952341/changeStatus/1586903857401695-5-9808733977`
`customers/5176952341/changeStatus/1586903857401695-5-9821525216`

Please let me know if there is any other info I could provider.

**Comment by BenRKarl** [comment] 2020-04-15 14:40
Thanks @j-walker23 I'll continue looking into the problem and respond here with any updates.

**Comment by BenRKarl** [comment] 2021-04-15 17:20
@j-walker23 sorry for the delayed response here. I'm currently not able to reproduce this and believe it has since been fixed, but please reopen the issue if you're still seeing this error.

**Closed by BenRKarl** 2021-04-15 17:20 UTC
Labels: P2, bug

**Comment by j-walker23** [comment] 2021-04-15 20:26
That was back in beta, i would bet it's fixed too. 
Thanks for your response!
