### ISSUE TITLE
ConversionUploadService GRPC Internal error encountered

### ISSUE THREAD

**Issue by dafi-blinkhealth** [googleads/google-ads-python#82] opened 2019-04-15 19:54 UTC
Hi,

I'm trying to upload offline conversion using ConversionUploadService, and I've been receiving `500 Internal error encountered` 

Here's the code:
```
conversion_upload_service = client.get_service('ConversionUploadService', version='v1')
conversion_upload_service.upload_click_conversions(<customer_id>, <conversions>, <partial_failure>)
```

Error stack trace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/muhammad.khadafi/.pyenv/versions/2.7.15/lib/python2.7/site-packages/google/ads/google_ads/v1/services/conversion_upload_service_client.py", line 220, in upload_click_conversions
    request, retry=retry, timeout=timeout, metadata=metadata)
  File "/Users/muhammad.khadafi/.pyenv/versions/2.7.15/lib/python2.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/muhammad.khadafi/.pyenv/versions/2.7.15/lib/python2.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "/Users/muhammad.khadafi/.pyenv/versions/2.7.15/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
google.api_core.exceptions.InternalServerError: 500 Internal error encountered.
```

errors from `google.api_core.exceptions.GoogleAPICallError` shows me:
```
[<_Rendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Internal error encountered."
	debug_error_string = "{"created":"@1555357512.579840000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Internal error encountered.","grpc_status":13}"
>]
```

I've tried this on Python 2.7.15 and 3.6.6

I've mentioned this on https://github.com/googleads/google-ads-python/issues/68, but the ticket was closed when it was resolved for the original poster. However, it still applies to my problem.

Any help would be greatly appreciated. Thanks!

Regards,
Dafi

**Comment by BenRKarl** [comment] 2019-04-22 06:03
Hi @dafi-blinkhealth thanks for sharing the stack trace. I'm going to try to reproduce the issue and look into it a bit more and will follow up here once I'm able to gather more information for you.

**Comment by BenRKarl** [comment] 2019-05-10 14:30
@dafi-blinkhealth Apologies for the delayed response. I haven't been able to reproduce this issue, are you continuing to have the same problem with newer versions of the API?

I'm going to close this out for now in case this was due to some temporary API issues that have since been resolved, but please reopen the issue if this persists.

**Closed by BenRKarl** 2019-05-10 14:30 UTC
